In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
%matplotlib inline

# Project 1

The purpose of this assignment is to give you an introduction to machine learning by implementing two
fairly simple learning algorithms. These two algorithms are called Winnow-2 (introduced in Module 01)
and Naïve Bayes (introduced in Module 02). Feel free to read ahead in the book if you want to get started
on Naïve Bayes early. For this assignment, you will use the following five datasets that you will download
from the UCI Machine Learning Repository 1 , namely:

## Data Export Step 1

Download the five (5) data sets from the UCI Machine Learning repository. You can find this repository
at http://archive.ics.uci.edu/ml/. All of the specific URLs are also provided above. Again, all
of the data sets are available in Blackboard as well.

In [3]:
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import random
import patsy
import sklearn.linear_model as linear

sns.set(style="whitegrid")
# load whatever other libraries you need including models.py

### Breast Cancer

There are 16 instances in Groups 1 to 6 that contain a single missing (i.e., unavailable) attribute value, now denoted by "?".

In [4]:
BreastCancer = pd.read_csv("breast-cancer-wisconsin.data", sep = ',')
BreastCancer.columns = ["Sample_code_number", "Clump_Thickness","Uniformity_CellSize", "Uniformity_CellShape","MarginalAdhesion","SE_CellSize","BareNuclei","BlandChromatin", "NormalNucleoli", "Mitoses", "Class"]
BreastCancer

,Sample_code_number,Clump_Thickness,Uniformity_CellSize,Uniformity_CellShape,MarginalAdhesion,SE_CellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

### Glass

Missing Attribute Values: None

In [5]:
Glass = pd.read_csv("glass.data", sep = ',')
Glass.columns = ["ID", "RefractiveIndex","Sodium", "Mag","Alum","Silicon","K","Calcium", "Barium", "Iron", "GlassType"]
Glass

,ID,RefractiveIndex,Sodium,Mag,Alum,Silicon,K,Calcium,Barium,Iron,GlassType
0,2,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.00,1
1,3,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.00,1
2,4,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.00,1
3,5,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.00,1
4,6,1.51596,12.79,3.61,1.62,72.97,0.64,8.07,0.00,0.26,1
...,...,...,...,...,...,...,...,...,...,...,...
208,210,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.00,7
209,211,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.00,7
210,212,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.00,7
211,213,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.00,7
212,214,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.00,7

### Iris

Missing attrubute value None

In [6]:
Iris = pd.read_csv("iris.data", sep = ',')
Iris.columns = ["Sepal_L", "Sepal_W","Petal_L", "Petal_W","Class"]
Iris

     Sepal_L  Sepal_W  Petal_L  Petal_W           Class
0        4.9      3.0      1.4      0.2     Iris-setosa
1        4.7      3.2      1.3      0.2     Iris-setosa
2        4.6      3.1      1.5      0.2     Iris-setosa
3        5.0      3.6      1.4      0.2     Iris-setosa
4        5.4      3.9      1.7      0.4     Iris-setosa
..       ...      ...      ...      ...             ...
144      6.7      3.0      5.2      2.3  Iris-virginica
145      6.3      2.5      5.0      1.9  Iris-virginica
146      6.5      3.0      5.2      2.0  Iris-virginica
147      6.2      3.4      5.4      2.3  Iris-virginica
148      5.9      3.0      5.1      1.8  Iris-virginica

[149 rows x 5 columns]

### Soybean

Number of Missing Attribute Values: 0

In [7]:
SoyBean = pd.read_csv("soybean-small.data", sep = ',')
SoyBean

,4,0,2,1,1.1,1.2,0.1,1.3,0.2,2.1,...,0.10,0.11,4.1,0.12,0.13,0.14,0.15,0.16,0.17,D1
0,5,0,2,1,0,3,1,1,1,2,...,0,0,4,0,0,0,0,0,0,D1
1,3,0,2,1,0,2,0,2,1,1,...,0,0,4,0,0,0,0,0,0,D1
2,6,0,2,1,0,1,1,1,0,0,...,0,0,4,0,0,0,0,0,0,D1
3,4,0,2,1,0,3,0,2,0,2,...,0,0,4,0,0,0,0,0,0,D1
4,5,0,2,1,0,2,0,1,1,0,...,0,0,4,0,0,0,0,0,0,D1
5,3,0,2,1,0,2,1,1,0,1,...,0,0,4,0,0,0,0,0,0,D1
6,3,0,2,1,0,1,0,2,1,2,...,0,0,4,0,0,0,0,0,0,D1
7,6,0,2,1,0,3,0,1,1,1,...,0,0,4,0,0,0,0,0,0,D1
8,6,0,2,1,0,1,0,1,0,2,...,0,0,4,0,0,0,0,0,0,D1
9,6,0,0,2,1,0,2,1,0,0,...,1,0,4,0,0,0,0,0,0,D2
10,4,0,0,1,0,2,3,1,1,1,...,1,0,4,0,0,0,0,0,0,D2
11,5,0,0,2,0,3,2,1,0,2,...,1,0,4,0,0,0,0,0,0,D2
12,6,0,0,1,1,3,3,1,1,0,...,1,0,4,0,0,0,0,0,0,D2
13,3,0,0,2,1,0,2,1,0,1,...,1,0,4,0,0,0,0,0,0,D2
14,4,0,0,1,1,1,3,1,1,1,...,1,0,4,0,0,0,0,0,0,D2
15,3,0,0,1,0,1,2,1,0,0,...,1,0,4,0,0,0,0,0,0,D2
16,5,0,0,2,1,2,2,1,0,2,...,1,0,4,0,0,0,0,0,0,D2
17,6,0,0,2,0,1,3,1,1,0,...,1,0,4,0,0,0,0,0,0,D2
18,5,0,0,2,1,3,3,1,1,2,...,1,0,4,0,0,0,0,0,0,D2
19,0,1,2,0,0,1,1,1,1,1,...,0,3,4,0,0,0,0,0,0,D3
20,2,1,2,0,0,3,1,2,0,1,...,0,3,4,0,0,0,0,0,0,D3
21,2,1,2,0,0,2,1,1,0,2,...,0,3,4,0,0,0,0,0,0,D3
22,0,1,2,0,0,0,1,1,1,2,...,0,3,4,0,0,0,0,0,0,D3
23,0,1,2,0,0,2,1,1,1,1,...,0,3,4,0,0,0,0,0,0,D3
24,4,0,2,0,1,0,1,2,0,2,...,0,3,4,0,0,0,0,0,0,D3
25,2,1,2,0,0,3,1,2,0,2,...,0,3,4,0,0,0,0,0,0,D3
26,0,1,2,0,0,0,1,1,0,1,...,0,3,4,0,0,0,0,0,1,D3
27,3,0,2,0,1,3,1,2,0,1,...,0,3,4,0,0,0,0,0,0,D3
28,0,1,2,0,0,1,1,2,1,2,...,0,3,4,0,0,0,0,0,0,D3
29,2,1,2,1,1,3,1,2,1,2,...,0,3,4,0,0,0,0,0,1,D4
30,0,1,1,1,0,1,1,1,0,0,...,0,3,4,0,0,0,0,0,1,D4
31,3,1,2,0,0,1,1,2,1,0,...,0,3,4,0,0,0,0,0,1,D4
32,2,1,2,1,1,1,1,2,0,2,...,0,3,4,0,0,0,0,0,1,D4
33,1,1,2,0,0,3,1,1,1,2,...,0,3,4,0,0,0,0,0,1,D4
34,1,1,2,1,0,0,1,2,1,1,...,0,3,4,0,0,0,0,0,1,D4
35,0,1,2,1,0,3,1,1,0,0,...,0,3,4,0,0,0,0,0,1,D4
36,2,1,2,0,0,1,1,2,0,0,...,0,3,4,0,0,0,0,0,1,D4
37,3,1,2,0,0,2,1,2,1,1,...,0,3,4,0,0,0,0,0,1,D4
38,3,1,1,0,0,2,1,2,1,2,...,0,3,4,0,0,0,0,0,1,D4
39,0,1,2,1,1,1,1,1,0,0,...,0,3,4,0,0,0,0,0,1,D4
40,1,1,2,1,1,3,1,2,0,1,...,0,3,4,0,0,0,0,0,1,D4
41,1,1,2,0,0,0,1,2,1,0,...,0,3,4,0,0,0,0,0,1,D4
42,1,1,2,1,1,2,3,1,1,1,...,0,3,4,0,0,0,0,0,1,D4
43,2,1,1,0,0,3,1,2,0,2,...,0,3,4,0,0,0,0,0,1,D4
44,0,1,1,1,1,2,1,2,1,0,...,0,3,4,0,0,0,0,0,1,D4
45,0,1,2,1,0,3,1,1,0,2,...,0,3,4,0,0,0,0,0,1,D4

In [8]:
Soycolumn = ['date',
'plantstand',
'precip',
'temp',
'hail',
'crophist',
'areadamaged',
'severity',
'seedtmt',
'germination',
'plantgrowth',
'leaves',
'leafspotshalo',
'leafspotsmarg',
'leafspotsize',
'leafshread',
'leafmalf',
'leafmild',
'stem',
'lodging',
'stemcankers',
'cankerlesion',
'fruitingbodies',
'externaldecay',
'mycelium',
'intdiscolor',
'sclerotia',
'fruitpods',
'fruitspots',
'seed',
'moldgrowth',
'seeddiscolor',
'seedsize',
'shriveling',
'roots','Distrubution']
SoyBean = pd.read_csv("soybean-small.data", sep = ',')
SoyBean.columns = Soycolumn
SoyBean

,date,plantstand,precip,temp,hail,crophist,areadamaged,severity,seedtmt,germination,...,sclerotia,fruitpods,fruitspots,seed,moldgrowth,seeddiscolor,seedsize,shriveling,roots,Distrubution
0,5,0,2,1,0,3,1,1,1,2,...,0,0,4,0,0,0,0,0,0,D1
1,3,0,2,1,0,2,0,2,1,1,...,0,0,4,0,0,0,0,0,0,D1
2,6,0,2,1,0,1,1,1,0,0,...,0,0,4,0,0,0,0,0,0,D1
3,4,0,2,1,0,3,0,2,0,2,...,0,0,4,0,0,0,0,0,0,D1
4,5,0,2,1,0,2,0,1,1,0,...,0,0,4,0,0,0,0,0,0,D1
5,3,0,2,1,0,2,1,1,0,1,...,0,0,4,0,0,0,0,0,0,D1
6,3,0,2,1,0,1,0,2,1,2,...,0,0,4,0,0,0,0,0,0,D1
7,6,0,2,1,0,3,0,1,1,1,...,0,0,4,0,0,0,0,0,0,D1
8,6,0,2,1,0,1,0,1,0,2,...,0,0,4,0,0,0,0,0,0,D1
9,6,0,0,2,1,0,2,1,0,0,...,1,0,4,0,0,0,0,0,0,D2
10,4,0,0,1,0,2,3,1,1,1,...,1,0,4,0,0,0,0,0,0,D2
11,5,0,0,2,0,3,2,1,0,2,...,1,0,4,0,0,0,0,0,0,D2
12,6,0,0,1,1,3,3,1,1,0,...,1,0,4,0,0,0,0,0,0,D2
13,3,0,0,2,1,0,2,1,0,1,...,1,0,4,0,0,0,0,0,0,D2
14,4,0,0,1,1,1,3,1,1,1,...,1,0,4,0,0,0,0,0,0,D2
15,3,0,0,1,0,1,2,1,0,0,...,1,0,4,0,0,0,0,0,0,D2
16,5,0,0,2,1,2,2,1,0,2,...,1,0,4,0,0,0,0,0,0,D2
17,6,0,0,2,0,1,3,1,1,0,...,1,0,4,0,0,0,0,0,0,D2
18,5,0,0,2,1,3,3,1,1,2,...,1,0,4,0,0,0,0,0,0,D2
19,0,1,2,0,0,1,1,1,1,1,...,0,3,4,0,0,0,0,0,0,D3
20,2,1,2,0,0,3,1,2,0,1,...,0,3,4,0,0,0,0,0,0,D3
21,2,1,2,0,0,2,1,1,0,2,...,0,3,4,0,0,0,0,0,0,D3
22,0,1,2,0,0,0,1,1,1,2,...,0,3,4,0,0,0,0,0,0,D3
23,0,1,2,0,0,2,1,1,1,1,...,0,3,4,0,0,0,0,0,0,D3
24,4,0,2,0,1,0,1,2,0,2,...,0,3,4,0,0,0,0,0,0,D3
25,2,1,2,0,0,3,1,2,0,2,...,0,3,4,0,0,0,0,0,0,D3
26,0,1,2,0,0,0,1,1,0,1,...,0,3,4,0,0,0,0,0,1,D3
27,3,0,2,0,1,3,1,2,0,1,...,0,3,4,0,0,0,0,0,0,D3
28,0,1,2,0,0,1,1,2,1,2,...,0,3,4,0,0,0,0,0,0,D3
29,2,1,2,1,1,3,1,2,1,2,...,0,3,4,0,0,0,0,0,1,D4
30,0,1,1,1,0,1,1,1,0,0,...,0,3,4,0,0,0,0,0,1,D4
31,3,1,2,0,0,1,1,2,1,0,...,0,3,4,0,0,0,0,0,1,D4
32,2,1,2,1,1,1,1,2,0,2,...,0,3,4,0,0,0,0,0,1,D4
33,1,1,2,0,0,3,1,1,1,2,...,0,3,4,0,0,0,0,0,1,D4
34,1,1,2,1,0,0,1,2,1,1,...,0,3,4,0,0,0,0,0,1,D4
35,0,1,2,1,0,3,1,1,0,0,...,0,3,4,0,0,0,0,0,1,D4
36,2,1,2,0,0,1,1,2,0,0,...,0,3,4,0,0,0,0,0,1,D4
37,3,1,2,0,0,2,1,2,1,1,...,0,3,4,0,0,0,0,0,1,D4
38,3,1,1,0,0,2,1,2,1,2,...,0,3,4,0,0,0,0,0,1,D4
39,0,1,2,1,1,1,1,1,0,0,...,0,3,4,0,0,0,0,0,1,D4
40,1,1,2,1,1,3,1,2,0,1,...,0,3,4,0,0,0,0,0,1,D4
41,1,1,2,0,0,0,1,2,1,0,...,0,3,4,0,0,0,0,0,1,D4
42,1,1,2,1,1,2,3,1,1,1,...,0,3,4,0,0,0,0,0,1,D4
43,2,1,1,0,0,3,1,2,0,2,...,0,3,4,0,0,0,0,0,1,D4
44,0,1,1,1,1,2,1,2,1,0,...,0,3,4,0,0,0,0,0,1,D4
45,0,1,2,1,0,3,1,1,0,2,...,0,3,4,0,0,0,0,0,1,D4

### Vote

Missing Attribute ?

In [9]:
Vote = pd.read_csv("house-votes-84.data", sep = ',')
Vote.columns = ["Class", "Handicap","Water", "Adoption","Physician", "SalvadorAid", "ReligionInSchool", "SatelitteTestBan", "NicaraguanAid","Missile", "Immigration","CorpCutBack","Education","Sue","Crime","DutyFreeExport","ExportAdmin"]
Vote.describe()

,Class,Handicap,Water,Adoption,Physician,SalvadorAid,ReligionInSchool,SatelitteTestBan,NicaraguanAid,Missile,Immigration,CorpCutBack,Education,Sue,Crime,DutyFreeExport,ExportAdmin
count,434,434,434,434,434,434,434,434,434,434,434,434,434,434,434,434,434
unique,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
top,democrat,n,y,y,n,y,y,y,y,y,y,n,n,y,y,n,y
freq,267,235,194,253,247,211,271,239,242,207,215,264,233,208,247,232,268

In [10]:
Vote["Handicap"].max()

'y'

## Data Pre Process Step 2

Pre-process each data set as necessary to handle missing data and non-Boolean data (both classes and
attributes).

### Breast Cancer Preproccess

In [11]:
f = open("breast-cancer-wisconsin.names", "r")
print(f.read())

Citation Request:
   This breast cancer databases was obtained from the University of Wisconsin
   Hospitals, Madison from Dr. William H. Wolberg.  If you publish results
   when using this database, then please include this information in your
   acknowledgements.  Also, please cite one or more of:

   1. O. L. Mangasarian and W. H. Wolberg: "Cancer diagnosis via linear
      programming", SIAM News, Volume 23, Number 5, September 1990, pp 1 & 18.

   2. William H. Wolberg and O.L. Mangasarian: "Multisurface method of
      pattern separation for medical diagnosis applied to breast cytology",
      Proceedings of the National Academy of Sciences, U.S.A., Volume 87,
      December 1990, pp 9193-9196.

   3. O. L. Mangasarian, R. Setiono, and W.H. Wolberg: "Pattern recognition
      via linear programming: Theory and application to medical diagnosis",
      in: "Large-scale numerical optimization", Thomas F. Coleman and Yuying
      Li, editors, SIAM Publications, Philadelphia 1990, pp 22-30.

   4. K. P. Bennett & O. L. Mangasarian: "Robust linear programming
      discrimination of two linearly inseparable sets", Optimization Methods
      and Software 1, 1992, 23-34 (Gordon & Breach Science Publishers).

1. Title: Wisconsin Breast Cancer Database (January 8, 1991)

2. Sources:
   -- Dr. WIlliam H. Wolberg (physician)
      University of Wisconsin Hospitals
      Madison, Wisconsin
      USA
   -- Donor: Olvi Mangasarian (mangasarian@cs.wisc.edu)
      Received by David W. Aha (aha@cs.jhu.edu)
   -- Date: 15 July 1992

3. Past Usage:

   Attributes 2 through 10 have been used to represent instances.
   Each instance has one of 2 possible classes: benign or malignant.

   1. Wolberg,~W.~H., \& Mangasarian,~O.~L. (1990). Multisurface method of
      pattern separation for medical diagnosis applied to breast cytology. In
      {\it Proceedings of the National Academy of Sciences}, {\it 87},
      9193--9196.
      -- Size of data set: only 369 instances (at that point in time)
      -- Collected classification results: 1 trial only
      -- Two pairs of parallel hyperplanes were found to be consistent with
         50% of the data
         -- Accuracy on remaining 50% of dataset: 93.5%
      -- Three pairs of parallel hyperplanes were found to be consistent with
         67% of data
         -- Accuracy on remaining 33% of dataset: 95.9%

   2. Zhang,~J. (1992). Selecting typical instances in instance-based
      learning.  In {\it Proceedings of the Ninth International Machine
      Learning Conference} (pp. 470--479).  Aberdeen, Scotland: Morgan
      Kaufmann.
      -- Size of data set: only 369 instances (at that point in time)
      -- Applied 4 instance-based learning algorithms
      -- Collected classification results averaged over 10 trials
      -- Best accuracy result:
         -- 1-nearest neighbor: 93.7%
         -- trained on 200 instances, tested on the other 169
      -- Also of interest:
         -- Using only typical instances: 92.2% (storing only 23.1 instances)
         -- trained on 200 instances, tested on the other 169

4. Relevant Information:

   Samples arrive periodically as Dr. Wolberg reports his clinical cases.
   The database therefore reflects this chronological grouping of the data.
   This grouping information appears immediately below, having been removed
   from the data itself:

     Group 1: 367 instances (January 1989)
     Group 2:  70 instances (October 1989)
     Group 3:  31 instances (February 1990)
     Group 4:  17 instances (April 1990)
     Group 5:  48 instances (August 1990)
     Group 6:  49 instances (Updated January 1991)
     Group 7:  31 instances (June 1991)
     Group 8:  86 instances (November 1991)
     -----------------------------------------
     Total:   699 points (as of the donated datbase on 15 July 1992)

   Note that the results summarized above in Past Usage refer to a dataset
   of size 369, while Group 1 has only 367 instances.  This is because it
   originally contained 369 instances; 2 were removed.  The following
   statements summarizes changes to the original Group 1's set of data:

   #####  Group 1 : 367 points: 200B 167M (January 1989)
   #####  Revised Jan 10, 1991: Replaced zero bare nuclei in 1080185 & 1187805
   #####  Revised Nov 22,1991: Removed 765878,4,5,9,7,10,10,10,3,8,1 no record
   #####                  : Removed 484201,2,7,8,8,4,3,10,3,4,1 zero epithelial
   #####                  : Changed 0 to 1 in field 6 of sample 1219406
   #####                  : Changed 0 to 1 in field 8 of following sample:
   #####                  : 1182404,2,3,1,1,1,2,0,1,1,1

5. Number of Instances: 699 (as of 15 July 1992)

6. Number of Attributes: 10 plus the class attribute

7. Attribute Information: (class attribute has been moved to last column)

   #  Attribute                     Domain
   -- -----------------------------------------
   1. Sample code number            id number
   2. Clump Thickness               1 - 10
   3. Uniformity of Cell Size       1 - 10
   4. Uniformity of Cell Shape      1 - 10
   5. Marginal Adhesion             1 - 10
   6. Single Epithelial Cell Size   1 - 10
   7. Bare Nuclei                   1 - 10
   8. Bland Chromatin               1 - 10
   9. Normal Nucleoli               1 - 10
  10. Mitoses                       1 - 10
  11. Class:                        (2 for benign, 4 for malignant)

8. Missing attribute values: 16

   There are 16 instances in Groups 1 to 6 that contain a single missing
   (i.e., unavailable) attribute value, now denoted by "?".

9. Class distribution:

   Benign: 458 (65.5%)
   Malignant: 241 (34.5%)

In [12]:
NumberOfDataDropped = 0
for Attribute in ["Sample_code_number", "Clump_Thickness","Uniformity_CellSize", "Uniformity_CellShape","MarginalAdhesion","SE_CellSize","BareNuclei","BlandChromatin", "NormalNucleoli", "Mitoses", "Class"]:
    for i in BreastCancer.query(''+Attribute+' == "?"').index:
        BreastCancer=BreastCancer.drop(i)
        NumberOfDataDropped=NumberOfDataDropped + 1

    
print(NumberOfDataDropped)

16

In [13]:
BreastCancer['BareNuclei'].describe()

count     682
unique     10
top         1
freq      401
Name: BareNuclei, dtype: object

In [14]:
BreastCancer.describe()

,Sample_code_number,Clump_Thickness,Uniformity_CellSize,Uniformity_CellShape,MarginalAdhesion,SE_CellSize,BlandChromatin,NormalNucleoli,Mitoses,Class
count,6.820000e+02,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000
mean,1.076833e+06,4.441349,3.153959,3.218475,2.832845,3.236070,3.445748,2.872434,1.604106,2.700880
std,6.210926e+05,2.822751,3.066285,2.989568,2.865805,2.224214,2.451435,3.054065,1.733792,0.954916
min,6.337500e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.774540e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171820e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238741e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

Object type change to Int

In [15]:
BreastCancer['BareNuclei']=pd.to_numeric(BreastCancer['BareNuclei'])
BreastCancer

,Sample_code_number,Clump_Thickness,Uniformity_CellSize,Uniformity_CellShape,MarginalAdhesion,SE_CellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [16]:
# create a list of our conditions
conditions = [
    (BreastCancer['Class'] == 2),
    (BreastCancer['Class'] == 4)
    ]


# create a list of the values we want to assign for each condition
values = [1, 0]

# create a new column and use np.select to assign values to it using our lists as arguments
BreastCancer['Class'] = np.select(conditions, values)
# display updated DataFrame
BreastCancer

,Sample_code_number,Clump_Thickness,Uniformity_CellSize,Uniformity_CellShape,MarginalAdhesion,SE_CellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,1002945,5,4,4,5,7,10,3,2,1,1
1,1015425,3,1,1,1,2,2,3,1,1,1
2,1016277,6,8,8,1,3,4,3,7,1,1
3,1017023,4,1,1,3,2,1,3,1,1,1
4,1017122,8,10,10,8,7,10,9,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,1
694,841769,2,1,1,1,2,1,1,1,1,1
695,888820,5,10,10,3,7,3,8,10,2,0
696,897471,4,8,6,4,3,4,10,6,1,0
697,897471,4,8,8,5,4,5,10,4,1,0

### Glass Pre Proccess

In [17]:
f = open("glass.names", "r")
print(f.read())

1. Title: Glass Identification Database

2. Sources:
    (a) Creator: B. German
        -- Central Research Establishment
           Home Office Forensic Science Service
           Aldermaston, Reading, Berkshire RG7 4PN
    (b) Donor: Vina Spiehler, Ph.D., DABFT
               Diagnostic Products Corporation
               (213) 776-0180 (ext 3014)
    (c) Date: September, 1987

3. Past Usage:
    -- Rule Induction in Forensic Science
       -- Ian W. Evett and Ernest J. Spiehler
       -- Central Research Establishment
          Home Office Forensic Science Service
          Aldermaston, Reading, Berkshire RG7 4PN
       -- Unknown technical note number (sorry, not listed here)
       -- General Results: nearest neighbor held its own with respect to the
             rule-based system

4. Relevant Information:n
      Vina conducted a comparison test of her rule-based system, BEAGLE, the
      nearest-neighbor algorithm, and discriminant analysis.  BEAGLE is
      a product available through VRS Consulting, Inc.; 4676 Admiralty Way,
      Suite 206; Marina Del Ray, CA 90292 (213) 827-7890 and FAX: -3189.
      In determining whether the glass was a type of "float" glass or not,
      the following results were obtained (# incorrect answers):

             Type of Sample                            Beagle   NN    DA
             Windows that were float processed (87)     10      12    21
             Windows that were not:            (76)     19      16    22

      The study of classification of types of glass was motivated by
      criminological investigation.  At the scene of the crime, the glass left
      can be used as evidence...if it is correctly identified!

5. Number of Instances: 214

6. Number of Attributes: 10 (including an Id#) plus the class attribute
   -- all attributes are continuously valued

7. Attribute Information:
   1. Id number: 1 to 214
   2. RI: refractive index
   3. Na: Sodium (unit measurement: weight percent in corresponding oxide, as
                  are attributes 4-10)
   4. Mg: Magnesium
   5. Al: Aluminum
   6. Si: Silicon
   7. K: Potassium
   8. Ca: Calcium
   9. Ba: Barium
  10. Fe: Iron
  11. Type of glass: (class attribute)
      -- 1 building_windows_float_processed
      -- 2 building_windows_non_float_processed
      -- 3 vehicle_windows_float_processed
      -- 4 vehicle_windows_non_float_processed (none in this database)
      -- 5 containers
      -- 6 tableware
      -- 7 headlamps

8. Missing Attribute Values: None

Summary Statistics:
Attribute:   Min     Max      Mean     SD      Correlation with class
 2. RI:       1.5112  1.5339   1.5184  0.0030  -0.1642
 3. Na:      10.73   17.38    13.4079  0.8166   0.5030
 4. Mg:       0       4.49     2.6845  1.4424  -0.7447
 5. Al:       0.29    3.5      1.4449  0.4993   0.5988
 6. Si:      69.81   75.41    72.6509  0.7745   0.1515
 7. K:        0       6.21     0.4971  0.6522  -0.0100
 8. Ca:       5.43   16.19     8.9570  1.4232   0.0007
 9. Ba:       0       3.15     0.1750  0.4972   0.5751
10. Fe:       0       0.51     0.0570  0.0974  -0.1879

9. Class Distribution: (out of 214 total instances)
    -- 163 Window glass (building windows and vehicle windows)
       -- 87 float processed
          -- 70 building windows
          -- 17 vehicle windows
       -- 76 non-float processed
          -- 76 building windows
          -- 0 vehicle windows
    -- 51 Non-window glass
       -- 13 containers
       -- 9 tableware
       -- 29 headlamps

### Iris Pre Proccess

In [18]:
f = open("iris.names", "r")
print(f.read())

1. Title: Iris Plants Database
	Updated Sept 21 by C.Blake - Added discrepency information

2. Sources:
     (a) Creator: R.A. Fisher
     (b) Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
     (c) Date: July, 1988

3. Past Usage:
   - Publications: too many to mention!!!  Here are a few.
   1. Fisher,R.A. "The use of multiple measurements in taxonomic problems"
      Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions
      to Mathematical Statistics" (John Wiley, NY, 1950).
   2. Duda,R.O., & Hart,P.E. (1973) Pattern Classification and Scene Analysis.
      (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
   3. Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
      Structure and Classification Rule for Recognition in Partially Exposed
      Environments".  IEEE Transactions on Pattern Analysis and Machine
      Intelligence, Vol. PAMI-2, No. 1, 67-71.
      -- Results:
         -- very low misclassification rates (0% for the setosa class)
   4. Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE
      Transactions on Information Theory, May 1972, 431-433.
      -- Results:
         -- very low misclassification rates again
   5. See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al's AUTOCLASS II
      conceptual clustering system finds 3 classes in the data.

4. Relevant Information:
   --- This is perhaps the best known database to be found in the pattern
       recognition literature.  Fisher's paper is a classic in the field
       and is referenced frequently to this day.  (See Duda & Hart, for
       example.)  The data set contains 3 classes of 50 instances each,
       where each class refers to a type of iris plant.  One class is
       linearly separable from the other 2; the latter are NOT linearly
       separable from each other.
   --- Predicted attribute: class of iris plant.
   --- This is an exceedingly simple domain.
   --- This data differs from the data presented in Fishers article
	(identified by Steve Chadwick,  spchadwick@espeedaz.net )
	The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa"
	where the error is in the fourth feature.
	The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa"
	where the errors are in the second and third features.

5. Number of Instances: 150 (50 in each of three classes)

6. Number of Attributes: 4 numeric, predictive attributes and the class

7. Attribute Information:
   1. sepal length in cm
   2. sepal width in cm
   3. petal length in cm
   4. petal width in cm
   5. class:
      -- Iris Setosa
      -- Iris Versicolour
      -- Iris Virginica

8. Missing Attribute Values: None

Summary Statistics:
	         Min  Max   Mean    SD   Class Correlation
   sepal length: 4.3  7.9   5.84  0.83    0.7826
    sepal width: 2.0  4.4   3.05  0.43   -0.4194
   petal length: 1.0  6.9   3.76  1.76    0.9490  (high!)
    petal width: 0.1  2.5   1.20  0.76    0.9565  (high!)

9. Class Distribution: 33.3% for each of 3 classes.

In [19]:
Iris["Class"].describe

<bound method NDFrame.describe of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: Class, Length: 149, dtype: object>

In [20]:
# create a list of our conditions
conditions = [
    (Iris['Class'] == "Iris-setosa"),
    (Iris['Class'] == "Iris-virginica"),
    (Iris['Class'] == "Iris-versicolor")
    ]

# create a list of the values we want to assign for each condition
values = [0, 1, 2]

# create a new column and use np.select to assign values to it using our lists as arguments
Iris['Class'] = np.select(conditions, values)
# display updated DataFrame
Iris.describe()

          Sepal_L     Sepal_W     Petal_L     Petal_W       Class
count  149.000000  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369    1.006711
std      0.828594    0.433499    1.759651    0.761292    0.817847
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.400000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

### Soybean Pre Proccess

In [21]:
f = open("soybean-small.names", "r")
print(f.read())

1. Title: Small Soybean Database

2. Sources:
     (a) Michalski,R.S. Learning by being told and learning from
         examples: an experimental comparison of the two methodes of knowledge
         acquisition in the context of developing an expert system for soybean
         desease diagnoiss", International Journal of Policy Analysis and
         Information Systems, 1980, 4(2), 125-161.
     (b) Donor: Doug Fisher (dfisher%vuse@uunet.uucp)
     (c) Date: 1987

3. Past Usage:
     See the soybean-large.names

4. Relevant Information Paragraph:
     A small subset of the original soybean database.  See the reference
     for Fisher and Schlimmer in soybean-large.names for more information.

     Steven Souders wrote:

    > Figure 15 in the Michalski and Stepp paper (PAMI-82) says that the
    > discriminant values for the attribute CONDITION OF FRUIT PODS for the
    > classes Rhizoctonia Root Rot and Phytophthora Rot are "few or none"
    > and "irrelevant" respectively.  However, in the SOYBEAN-SMALL dataset
    > I got from UCI, the value for this attribute is "dna" (does not apply)
    > for both classes.  I show the actual data below for cases D3
    > (Rhizoctonia Root Rot) and D4 (Phytophthora Rot).  According to the
    > attribute names given in soybean-large.names, FRUIT-PODS is attribute
    > #28.  If you look at column 28 in the data below (marked with arrows)
    > you'll notice that all cases of D3 and D4 have the same value.  Thus,
    > the SOYBEAN-SMALL dataset from UCI could NOT have produced the results
    > in the Michalski and Stepp paper.

    I do not have that paper, but have found what is probably a later
    variation of that figure in Stepp's dissertation, which lists the
    value "normal" for the first 2 classes and "irrelevant" for the latter
    2 classes.  I believe that "irrelevant" is used here as a synonym for
    "not-applicable", "dna", and "does-not-apply".  I believe that there
    is a mis-print in the figure he read in their PAMI-83 article.

    I have checked over each attribute value in this database.  It
    corresponds exactly with the copies listed in both Stepp's and Fisher's
    dissertations.

5. Number of Instances: 47

6. Number of Attributes: 35 (all have been nominalized)
     -- All attributes here appear with numeric values

7. Attribute Information:
     -- derivable from soybean-large.names

8. Number of Missing Attribute Values: 0

9. Class Distribution:
   1. D1: 10
   2. D2: 10
   3. D3: 10
   4. D4: 17

In [22]:
SoycolumnCheck = ['date',
'plantstand',
'precip',
'temp',
'hail',
'crophist',
'areadamaged',
'severity',
'seedtmt',
'germination',
'plantgrowth',
'leaves',
'leafspotshalo',
'leafspotsmarg',
'leafspotsize',
'leafshread',
'leafmalf',
'leafmild',
'stem',
'lodging',
'stemcankers',
'cankerlesion',
'fruitingbodies',
'externaldecay',
'mycelium',
'intdiscolor',
'sclerotia',
'fruitpods',
'fruitspots',
'seed',
'moldgrowth',
'seeddiscolor',
'seedsize',
'shriveling',
'roots']
for Attribute in SoycolumnCheck:
    if SoyBean[Attribute].mean() == 0.0:
        print(Attribute)
        SoyBean = SoyBean.drop(columns = Attribute)

leafspotshalo
leafshread
leafmalf
leafmild
seed
moldgrowth
seeddiscolor
seedsize
shriveling

In [23]:
SoyBean

,date,plantstand,precip,temp,hail,crophist,areadamaged,severity,seedtmt,germination,...,cankerlesion,fruitingbodies,externaldecay,mycelium,intdiscolor,sclerotia,fruitpods,fruitspots,roots,Distrubution
0,5,0,2,1,0,3,1,1,1,2,...,0,1,1,0,0,0,0,4,0,D1
1,3,0,2,1,0,2,0,2,1,1,...,0,1,1,0,0,0,0,4,0,D1
2,6,0,2,1,0,1,1,1,0,0,...,1,1,1,0,0,0,0,4,0,D1
3,4,0,2,1,0,3,0,2,0,2,...,1,1,1,0,0,0,0,4,0,D1
4,5,0,2,1,0,2,0,1,1,0,...,1,1,1,0,0,0,0,4,0,D1
5,3,0,2,1,0,2,1,1,0,1,...,0,1,1,0,0,0,0,4,0,D1
6,3,0,2,1,0,1,0,2,1,2,...,0,1,1,0,0,0,0,4,0,D1
7,6,0,2,1,0,3,0,1,1,1,...,1,1,1,0,0,0,0,4,0,D1
8,6,0,2,1,0,1,0,1,0,2,...,1,1,1,0,0,0,0,4,0,D1
9,6,0,0,2,1,0,2,1,0,0,...,3,0,0,0,2,1,0,4,0,D2
10,4,0,0,1,0,2,3,1,1,1,...,3,0,0,0,2,1,0,4,0,D2
11,5,0,0,2,0,3,2,1,0,2,...,3,0,0,0,2,1,0,4,0,D2
12,6,0,0,1,1,3,3,1,1,0,...,3,0,0,0,2,1,0,4,0,D2
13,3,0,0,2,1,0,2,1,0,1,...,3,0,0,0,2,1,0,4,0,D2
14,4,0,0,1,1,1,3,1,1,1,...,3,0,0,0,2,1,0,4,0,D2
15,3,0,0,1,0,1,2,1,0,0,...,3,0,0,0,2,1,0,4,0,D2
16,5,0,0,2,1,2,2,1,0,2,...,3,0,0,0,2,1,0,4,0,D2
17,6,0,0,2,0,1,3,1,1,0,...,3,0,0,0,2,1,0,4,0,D2
18,5,0,0,2,1,3,3,1,1,2,...,3,0,0,0,2,1,0,4,0,D2
19,0,1,2,0,0,1,1,1,1,1,...,1,0,1,1,0,0,3,4,0,D3
20,2,1,2,0,0,3,1,2,0,1,...,1,0,1,0,0,0,3,4,0,D3
21,2,1,2,0,0,2,1,1,0,2,...,1,0,1,1,0,0,3,4,0,D3
22,0,1,2,0,0,0,1,1,1,2,...,1,0,1,0,0,0,3,4,0,D3
23,0,1,2,0,0,2,1,1,1,1,...,1,0,1,0,0,0,3,4,0,D3
24,4,0,2,0,1,0,1,2,0,2,...,1,0,1,1,0,0,3,4,0,D3
25,2,1,2,0,0,3,1,2,0,2,...,1,0,1,1,0,0,3,4,0,D3
26,0,1,2,0,0,0,1,1,0,1,...,1,0,1,0,0,0,3,4,1,D3
27,3,0,2,0,1,3,1,2,0,1,...,1,0,1,1,0,0,3,4,0,D3
28,0,1,2,0,0,1,1,2,1,2,...,1,0,1,0,0,0,3,4,0,D3
29,2,1,2,1,1,3,1,2,1,2,...,2,0,1,0,0,0,3,4,1,D4
30,0,1,1,1,0,1,1,1,0,0,...,2,0,0,0,0,0,3,4,1,D4
31,3,1,2,0,0,1,1,2,1,0,...,2,0,0,0,0,0,3,4,1,D4
32,2,1,2,1,1,1,1,2,0,2,...,2,0,1,0,0,0,3,4,1,D4
33,1,1,2,0,0,3,1,1,1,2,...,2,0,0,0,0,0,3,4,1,D4
34,1,1,2,1,0,0,1,2,1,1,...,2,0,0,0,0,0,3,4,1,D4
35,0,1,2,1,0,3,1,1,0,0,...,2,0,0,0,0,0,3,4,1,D4
36,2,1,2,0,0,1,1,2,0,0,...,2,0,0,0,0,0,3,4,1,D4
37,3,1,2,0,0,2,1,2,1,1,...,2,0,0,0,0,0,3,4,1,D4
38,3,1,1,0,0,2,1,2,1,2,...,2,0,0,0,0,0,3,4,1,D4
39,0,1,2,1,1,1,1,1,0,0,...,2,0,1,0,0,0,3,4,1,D4
40,1,1,2,1,1,3,1,2,0,1,...,2,0,1,0,0,0,3,4,1,D4
41,1,1,2,0,0,0,1,2,1,0,...,2,0,0,0,0,0,3,4,1,D4
42,1,1,2,1,1,2,3,1,1,1,...,2,0,1,0,0,0,3,4,1,D4
43,2,1,1,0,0,3,1,2,0,2,...,2,0,0,0,0,0,3,4,1,D4
44,0,1,1,1,1,2,1,2,1,0,...,2,0,1,0,0,0,3,4,1,D4
45,0,1,2,1,0,3,1,1,0,2,...,2,0,0,0,0,0,3,4,1,D4

In [24]:
# create a list of our conditions
conditions = [
    (SoyBean['Distrubution'] == "D1"),
    (SoyBean['Distrubution'] == "D2"),
    (SoyBean['Distrubution'] == "D3"),
    (SoyBean['Distrubution'] == "D4")
    ]

# create a list of the values we want to assign for each condition
values = [1, 2, 3, 4]

# create a new column and use np.select to assign values to it using our lists as arguments
SoyBean['Distrubution'] = np.select(conditions, values)
# display updated DataFrame
SoyBean.describe()

,date,plantstand,precip,temp,hail,crophist,areadamaged,severity,seedtmt,germination,...,cankerlesion,fruitingbodies,externaldecay,mycelium,intdiscolor,sclerotia,fruitpods,fruitspots,roots,Distrubution
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.00000,46.000000,46.000000,46.000000,...,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.0,46.000000,46.000000
mean,2.673913,0.543478,1.478261,0.760870,0.304348,1.739130,1.23913,1.413043,0.500000,1.108696,...,1.717391,0.195652,0.543478,0.108696,0.434783,0.217391,1.760870,4.0,0.391304,2.760870
std,2.055392,0.503610,0.836371,0.672798,0.465215,1.083918,0.84813,0.497821,0.505525,0.822686,...,0.910752,0.401085,0.503610,0.314696,0.834058,0.417029,1.493464,0.0,0.493435,1.158251
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,0.000000,1.000000
25%,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.00000,1.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,0.000000,2.000000
50%,3.000000,1.000000,2.000000,1.000000,0.000000,2.000000,1.00000,1.000000,0.500000,1.000000,...,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,3.000000,4.0,0.000000,3.000000
75%,4.000000,1.000000,2.000000,1.000000,1.000000,3.000000,1.00000,2.000000,1.000000,2.000000,...,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,3.000000,4.0,1.000000,4.000000
max,6.000000,1.000000,2.000000,2.000000,1.000000,3.000000,3.00000,2.000000,1.000000,2.000000,...,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,4.0,1.000000,4.000000

Removed 9 Columns because they only had 0 in the whole colume so doesnst say much

### Vote Pre Proccess

In [25]:
f = open("house-votes-84.names", "r")
print(f.read())

1. Title: 1984 United States Congressional Voting Records Database

2. Source Information:
    (a) Source:  Congressional Quarterly Almanac, 98th Congress,
                 2nd session 1984, Volume XL: Congressional Quarterly Inc.
                 Washington, D.C., 1985.
    (b) Donor: Jeff Schlimmer (Jeffrey.Schlimmer@a.gp.cs.cmu.edu)
    (c) Date: 27 April 1987

3. Past Usage
   - Publications
     1. Schlimmer, J. C. (1987).  Concept acquisition through
        representational adjustment.  Doctoral dissertation, Department of
        Information and Computer Science, University of California, Irvine, CA.
        -- Results: about 90%-95% accuracy appears to be STAGGER's asymptote
     - Predicted attribute: party affiliation (2 classes)

4. Relevant Information:
      This data set includes votes for each of the U.S. House of
      Representatives Congressmen on the 16 key votes identified by the
      CQA.  The CQA lists nine different types of votes: voted for, paired
      for, and announced for (these three simplified to yea), voted
      against, paired against, and announced against (these three
      simplified to nay), voted present, voted present to avoid conflict
      of interest, and did not vote or otherwise make a position known
      (these three simplified to an unknown disposition).

5. Number of Instances: 435 (267 democrats, 168 republicans)

6. Number of Attributes: 16 + class name = 17 (all Boolean valued)

7. Attribute Information:
   1. Class Name: 2 (democrat, republican)
   2. handicapped-infants: 2 (y,n)
   3. water-project-cost-sharing: 2 (y,n)
   4. adoption-of-the-budget-resolution: 2 (y,n)
   5. physician-fee-freeze: 2 (y,n)
   6. el-salvador-aid: 2 (y,n)
   7. religious-groups-in-schools: 2 (y,n)
   8. anti-satellite-test-ban: 2 (y,n)
   9. aid-to-nicaraguan-contras: 2 (y,n)
  10. mx-missile: 2 (y,n)
  11. immigration: 2 (y,n)
  12. synfuels-corporation-cutback: 2 (y,n)
  13. education-spending: 2 (y,n)
  14. superfund-right-to-sue: 2 (y,n)
  15. crime: 2 (y,n)
  16. duty-free-exports: 2 (y,n)
  17. export-administration-act-south-africa: 2 (y,n)

8. Missing Attribute Values: Denoted by "?"

   NOTE: It is important to recognize that "?" in this database does
         not mean that the value of the attribute is unknown.  It
         means simply, that the value is not "yea" or "nay" (see
         "Relevant Information" section above).

   Attribute:  #Missing Values:
           1:  0
           2:  0
           3:  12
           4:  48
           5:  11
           6:  11
           7:  15
           8:  11
           9:  14
          10:  15
          11:  22
          12:  7
          13:  21
          14:  31
          15:  25
          16:  17
          17:  28

9. Class Distribution: (2 classes)
   1. 45.2 percent are democrat
   2. 54.8 percent are republican

Class predictiveness and predictability: Pr(C|A=V) and Pr(A=V|C)
 Attribute 1: (A = handicapped-infants)
  0.91;  1.21  (C=democrat; V=y)
  0.09;  0.10  (C=republican; V=y)
  0.43;  0.38  (C=democrat; V=n)
  0.57;  0.41  (C=republican; V=n)
  0.75;  0.03  (C=democrat; V=?)
  0.25;  0.01  (C=republican; V=?)
 Attribute 2: (A = water-project-cost-sharing)
  0.62;  0.45  (C=democrat; V=y)
  0.38;  0.23  (C=republican; V=y)
  0.62;  0.45  (C=democrat; V=n)
  0.38;  0.23  (C=republican; V=n)
  0.58;  0.10  (C=democrat; V=?)
  0.42;  0.06  (C=republican; V=?)
 Attribute 3: (A = adoption-of-the-budget-resolution)
  0.91;  0.87  (C=democrat; V=y)
  0.09;  0.07  (C=republican; V=y)
  0.17;  0.11  (C=democrat; V=n)
  0.83;  0.44  (C=republican; V=n)
  0.64;  0.03  (C=democrat; V=?)
  0.36;  0.01  (C=republican; V=?)
 Attribute 4: (A = physician-fee-freeze)
  0.08;  0.05  (C=democrat; V=y)
  0.92;  0.50  (C=republican; V=y)
  0.99;  0.92  (C=democrat; V=n)
  0.01;  0.01  (C=republican; V=n)
  0.73;  0.03  (C=democrat; V=?)
  0.27;  0.01  (C=republican; V=?)
 Attribute 5: (A = el-salvador-aid)
  0.26;  0.21  (C=democrat; V=y)
  0.74;  0.48  (C=republican; V=y)
  0.96;  0.75  (C=democrat; V=n)
  0.04;  0.02  (C=republican; V=n)
  0.80;  0.04  (C=democrat; V=?)
  0.20;  0.01  (C=republican; V=?)
 Attribute 6: (A = religious-groups-in-schools)
  0.45;  0.46  (C=democrat; V=y)
  0.55;  0.46  (C=republican; V=y)
  0.89;  0.51  (C=democrat; V=n)
  0.11;  0.05  (C=republican; V=n)
  0.82;  0.03  (C=democrat; V=?)
  0.18;  0.01  (C=republican; V=?)
 Attribute 7: (A = anti-satellite-test-ban)
  0.84;  0.75  (C=democrat; V=y)
  0.16;  0.12  (C=republican; V=y)
  0.32;  0.22  (C=democrat; V=n)
  0.68;  0.38  (C=republican; V=n)
  0.57;  0.03  (C=democrat; V=?)
  0.43;  0.02  (C=republican; V=?)
 Attribute 8: (A = aid-to-nicaraguan-contras)
  0.90;  0.82  (C=democrat; V=y)
  0.10;  0.07  (C=republican; V=y)
  0.25;  0.17  (C=democrat; V=n)
  0.75;  0.41  (C=republican; V=n)
  0.27;  0.01  (C=democrat; V=?)
  0.73;  0.03  (C=republican; V=?)
 Attribute 9: (A = mx-missile)
  0.91;  0.70  (C=democrat; V=y)
  0.09;  0.06  (C=republican; V=y)
  0.29;  0.22  (C=democrat; V=n)
  0.71;  0.45  (C=republican; V=n)
  0.86;  0.07  (C=democrat; V=?)
  0.14;  0.01  (C=republican; V=?)
 Attribute 10: (A = immigration)
  0.57;  0.46  (C=democrat; V=y)
  0.43;  0.28  (C=republican; V=y)
  0.66;  0.52  (C=democrat; V=n)
  0.34;  0.23  (C=republican; V=n)
  0.57;  0.01  (C=democrat; V=?)
  0.43;  0.01  (C=republican; V=?)
 Attribute 11: (A = synfuels-corporation-cutback)
  0.86;  0.48  (C=democrat; V=y)
  0.14;  0.06  (C=republican; V=y)
  0.48;  0.47  (C=democrat; V=n)
  0.52;  0.43  (C=republican; V=n)
  0.57;  0.04  (C=democrat; V=?)
  0.43;  0.03  (C=republican; V=?)
 Attribute 12: (A = education-spending)
  0.21;  0.13  (C=democrat; V=y)
  0.79;  0.42  (C=republican; V=y)
  0.91;  0.80  (C=democrat; V=n)
  0.09;  0.06  (C=republican; V=n)
  0.58;  0.07  (C=democrat; V=?)
  0.42;  0.04  (C=republican; V=?)
 Attribute 13: (A = superfund-right-to-sue)
  0.35;  0.27  (C=democrat; V=y)
  0.65;  0.42  (C=republican; V=y)
  0.89;  0.67  (C=democrat; V=n)
  0.11;  0.07  (C=republican; V=n)
  0.60;  0.06  (C=democrat; V=?)
  0.40;  0.03  (C=republican; V=?)
 Attribute 14: (A = crime)
  0.36;  0.34  (C=democrat; V=y)
  0.64;  0.49  (C=republican; V=y)
  0.98;  0.63  (C=democrat; V=n)
  0.02;  0.01  (C=republican; V=n)
  0.59;  0.04  (C=democrat; V=?)
  0.41;  0.02  (C=republican; V=?)
 Attribute 15: (A = duty-free-exports)
  0.92;  0.60  (C=democrat; V=y)
  0.08;  0.04  (C=republican; V=y)
  0.39;  0.34  (C=democrat; V=n)
  0.61;  0.44  (C=republican; V=n)
  0.57;  0.06  (C=democrat; V=?)
  0.43;  0.04  (C=republican; V=?)
 Attribute 16: (A = export-administration-act-south-africa)
  0.64;  0.65  (C=democrat; V=y)
  0.36;  0.30  (C=republican; V=y)
  0.19;  0.04  (C=democrat; V=n)
  0.81;  0.15  (C=republican; V=n)
  0.79;  0.31  (C=democrat; V=?)
  0.21;  0.07  (C=republican; V=?)

In [26]:
NumberOfDataDropped = 0
for Attribute in ["Class", "Handicap","Water", "Adoption","Physician", "SalvadorAid", "ReligionInSchool", "SatelitteTestBan", "NicaraguanAid","Missile", "Immigration","CorpCutBack","Education","Sue","Crime","DutyFreeExport","ExportAdmin"]:
    for i in Vote.query(''+Attribute+' == "?"').index:
        Vote=Vote.drop(i)
        NumberOfDataDropped=NumberOfDataDropped + 1

    
print(NumberOfDataDropped)
Vote

202

,Class,Handicap,Water,Adoption,Physician,SalvadorAid,ReligionInSchool,SatelitteTestBan,NicaraguanAid,Missile,Immigration,CorpCutBack,Education,Sue,Crime,DutyFreeExport,ExportAdmin
4,democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
7,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
18,democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
22,democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
24,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,democrat,n,y,y,n,n,y,y,y,y,n,y,n,n,y,y,y
425,democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
426,republican,n,n,n,y,y,y,y,y,n,y,n,y,y,y,n,y
429,republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
430,democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y

In [27]:
# create a list of our conditions
conditions = [
    (Vote['Class'] == "democrat"),
    (Vote['Class'] == "republican")
    ]

# create a list of the values we want to assign for each condition
values = [0, 1]

# create a new column and use np.select to assign values to it using our lists as arguments
Vote['Class'] = np.select(conditions, values)
# display updated DataFrame
Vote.describe()

            Class
count  232.000000
mean     0.465517
std      0.499888
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000

In [28]:
for Attribute in ["Handicap","Water", "Adoption","Physician", "SalvadorAid", "ReligionInSchool", "SatelitteTestBan", "NicaraguanAid","Missile", "Immigration","CorpCutBack","Education","Sue","Crime","DutyFreeExport","ExportAdmin"]:
   # create a list of our conditions
    conditions = [
        (Vote[Attribute] == "n"),
        (Vote[Attribute] == "y")
    ]

    # create a list of the values we want to assign for each condition
    values = [0, 1]

    # create a new column and use np.select to assign values to it using our lists as arguments
    Vote[Attribute] = np.select(conditions, values) 
    
    
    
Vote.describe()

,Class,Handicap,Water,Adoption,Physician,SalvadorAid,ReligionInSchool,SatelitteTestBan,NicaraguanAid,Missile,Immigration,CorpCutBack,Education,Sue,Crime,DutyFreeExport,ExportAdmin
count,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000
mean,0.465517,0.413793,0.461207,0.530172,0.487069,0.551724,0.642241,0.534483,0.512931,0.487069,0.551724,0.344828,0.465517,0.547414,0.642241,0.370690,0.814655
std,0.499888,0.493577,0.499571,0.500168,0.500913,0.498393,0.480377,0.499888,0.500913,0.500913,0.498393,0.476340,0.499888,0.498823,0.480377,0.484034,0.389417
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Training and Testing

### Winnow

In [29]:
import Winnow2

#### Breast Cancer

In [41]:
DataPath = "BreastCancer.Data"
TrainWeightFile = "Winnow/BreastCancer/TrainWeightFile.txt"
TrainOutFile = "Winnow/BreastCancer/TrainOutFile.txt"
TestStatsFile = "Winnow/BreastCancer/TestStatsFile.txt"
TestOutFile = "Winnow/BreastCancer/TestOutFile.txt"
Winnow2.Winnow(BreastCancer, DataPath, TrainWeightFile, TrainOutFile, TestStatsFile, TestOutFile)

----------------------------------------------------------
 Winnow2 Results
----------------------------------------------------------
Data Set : BreastCancer.Data


----------------------------
Weights of the Learned Model
----------------------------
Clump_Thickness : 0.25
Uniformity_CellSize : 0.5
Uniformity_CellShape : 1.0
MarginalAdhesion : 7.62939453125e-06
SE_CellSize : 1.0
BareNuclei : 0.001953125
BlandChromatin : 0.25
NormalNucleoli : 7.450580596923828e-09
Mitoses : 5.169878828456423e-26


-----------
Constants
-----------
THETA = 0.5
ALPHA = 2.0

-------------------------------------------------------
Learned Model Runs of the Training Data Set (in binary)
-------------------------------------------------------
[[1.168359e+06 8.000000e+00 2.000000e+00 ... 0.000000e+00 0.000000e+00
  1.000000e+00]
 [1.223426e+06 1.000000e+00 1.000000e+00 ... 0.000000e+00 0.000000e+00
  0.000000e+00]
 [1.296263e+06 4.000000e+00 1.000000e+00 ... 0.000000e+00 0.000000e+00
  0.000000e+00]
 ...
 [1.173681e+06 3.000000e+00 2.000000e+00 ... 0.000000e+00 0.000000e+00
  0.000000e+00]
 [1.218860e+06 1.000000e+00 1.000000e+00 ... 0.000000e+00 0.000000e+00
  0.000000e+00]
 [1.016634e+06 2.000000e+00 3.000000e+00 ... 0.000000e+00 0.000000e+00
  0.000000e+00]]


-------------------------------------------------------
Learned Model Runs of the Training Data Set (readable)
-------------------------------------------------------
     Sample_code_number Clump_Thickness Uniformity_CellSize  \
0             1168359.0               8                   2
1             1223426.0            True                True
2             1296263.0               4                True
3             1108449.0               5                   3
4             1277268.0               3                   3
..                  ...             ...                 ...
452           1166654.0              10                   3
453           1183596.0               3                True
454           1173681.0               3                   2
455           1218860.0            True                True
456           1016634.0               2                   3

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                      3             True           6          3
1                   True             True           2       True
2                   True             True           2       True
3                      3                4           2          4
4                   True             True           2       True
..                   ...              ...         ...        ...
452                    5             True          10          5
453                    3             True           3          4
454                 True             True           2          2
455                 True             True        True       True
456                 True             True           2       True

    BlandChromatin NormalNucleoli Mitoses  Class  Weighted Sum  \
0                7           True    True    0.0     32.000000
1                3           True    True    1.0     10.500000
2             True           True    True    1.0     11.500000
3                3              4    True    0.0     24.500000
4             True           True    True    1.0     12.250000
..             ...            ...     ...    ...           ...
452              3             10       2    0.0     19.759781
453           True           True    True    1.0      7.507820
454              3           True    True    1.0      5.503914
455              3           True    True    1.0      3.501961
456              2           True    True    1.0      5.501961

     Predicted Class True Positive False Positive False Negative  \
0                1.0            No            Yes             No
1                1.0           Yes             No             No
2                1.0           Yes             No             No
3                1.0            No            Yes             No
4                1.0           Yes             No             No
..               ...           ...            ...            ...
452              1.0            No            Yes             No
453              1.0           Yes             No             No
454              1.0           Yes             No             No
455              1.0           Yes             No             No
456              1.0           Yes             No             No

    True Negative Promote Demote
0              No      No    Yes
1              No      No     No
2              No      No     No
3              No      No    Yes
4              No      No     No
..            ...     ...    ...
452            No      No    Yes
453            No      No     No
454            No      No     No
455            No      No     No
456            No      No     No

[457 rows x 19 columns]
-------------------------------------------------------
Learned Model Predictions on Testing Data Set
-------------------------------------------------------
     Sample_code_number Clump_Thickness Uniformity_CellSize  \
0             1002945.0               5                   4
1             1015425.0               3                True
2             1041801.0               5                   3
3             1044572.0               8                   7
4             1047630.0               7                   4
..                  ...             ...                 ...
220            536708.0            True                True
221            695091.0               5                  10
222            714039.0               3                True
223            776715.0               3                True
224            897471.0               4                   8

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                      4                5           7         10
1                   True             True           2          2
2                      3                3           2          3
3                      5               10           7          9
4                      6                4           6       True
..                   ...              ...         ...        ...
220                 True             True           2       True
221                   10                5           4          5
222                 True             True           2       True
223                 True             True           3          2
224                    8                5           4          5

    BlandChromatin NormalNucleoli Mitoses  Class  Weighted Sum  \
0                3              2    True    1.0     15.019569
1                3           True    True    1.0      5.003914
2                4              4    True    0.0      8.755882
3                5              5       4    0.0     18.767654
4                4              3    True    0.0     16.751984
..             ...            ...     ...    ...           ...
220           True           True    True    1.0      4.001961
221              4              4    True    0.0     21.259804
222           True           True    True    1.0      4.501961
223           True           True    True    1.0      5.503914
224             10              4    True    0.0     19.509804

     Predicted Class True Positive False Positive False Negative True Negative
0                1.0           Yes             No             No            No
1                1.0           Yes             No             No            No
2                1.0            No            Yes             No            No
3                1.0            No            Yes             No            No
4                1.0            No            Yes             No            No
..               ...           ...            ...            ...           ...
220              1.0           Yes             No             No            No
221              1.0            No            Yes             No            No
222              1.0           Yes             No             No            No
223              1.0           Yes             No             No            No
224              1.0            No            Yes             No            No

[225 rows x 17 columns]


-------------------------------------------------------
Winnow2 Summary Statistics (Testing)
-------------------------------------------------------
Data Set : BreastCancer.Data

Number of Test Instances : 225
True Positives : 140
False Positives : 85
False Negatives : 0
True Negatives : 0
Accuracy : 62.22222222222222%

#### Glass

In [31]:
DataPath = "Glass.Data"
TrainWeightFile = "Winnow/Glass/TrainWeightFile.txt"
TrainOutFile = "Winnow/Glass/TrainOutFile.txt"
TestStatsFile = "Winnow/Glass/TestStatsFile.txt"
TestOutFile = "Winnow/Glass/TestOutFile.txt"
Winnow2.Winnow(Glass, DataPath, TrainWeightFile, TrainOutFile, TestStatsFile, TestOutFile)

----------------------------------------------------------
 Winnow2 Results
----------------------------------------------------------
Data Set : Glass.Data


----------------------------
Weights of the Learned Model
----------------------------
RefractiveIndex : 1.0
Sodium : 1.0
Mag : 1.0
Alum : 1.0
Silicon : 1.0
K : 1.0
Calcium : 1.0
Barium : 1.0
Iron : 1.0


-----------
Constants
-----------
THETA = 0.5
ALPHA = 2.0

-------------------------------------------------------
Learned Model Runs of the Training Data Set (in binary)
-------------------------------------------------------
[[ 94.        1.5159   13.24    ...   1.        0.        0.     ]
 [ 45.        1.51786  12.73    ...   0.        0.        0.     ]
 [100.        1.51811  12.96    ...   1.        0.        0.     ]
 ...
 [ 33.        1.51775  12.85    ...   0.        0.        0.     ]
 [ 95.        1.51629  12.71    ...   1.        0.        0.     ]
 [ 47.        1.51869  13.19    ...   0.        0.        0.     ]]


-------------------------------------------------------
Learned Model Runs of the Training Data Set (readable)
-------------------------------------------------------
        ID  RefractiveIndex  Sodium    Mag  Alum  Silicon     K  Calcium  \
0     94.0          1.51590   13.24   3.34  1.47    73.10  0.39     8.22
1     45.0          1.51786   12.73   3.43  1.19    72.95  0.62     8.76
2    100.0          1.51811   12.96   2.96  1.43    72.92   0.6     8.79
3    103.0          1.51820   12.62   2.76  0.83    73.81  0.35     9.42
4    105.0          1.52410   13.83    2.9  1.17    71.15  0.08    10.79
..     ...              ...     ...    ...   ...      ...   ...      ...
138   96.0          1.51860   13.36   3.43  1.43    72.26  0.51     8.60
139  173.0          1.51321   13.00  False  3.02    70.70  6.21     6.93
140   33.0          1.51775   12.85   3.48  1.23    72.97  0.61     8.56
141   95.0          1.51629   12.71   3.33  1.49    73.28  0.67     8.24
142   47.0          1.51869   13.19   3.37  1.18    72.72  0.57     8.83

    Barium   Iron  GlassType  Weighted Sum  Predicted Class True Positive  \
0    False  False        2.0     101.27590              1.0            No
1    False    0.3        1.0     101.49786              1.0           Yes
2     0.14  False        2.0     101.31811              1.0            No
3    False    0.2        2.0     101.50820              1.0            No
4    False  False        2.0     101.44410              1.0            No
..     ...    ...        ...           ...              ...           ...
138  False  False        2.0     101.10860              1.0            No
139  False  False        5.0     101.37321              1.0            No
140   0.09   0.22        1.0     101.52775              1.0           Yes
141  False  False        2.0     101.23629              1.0            No
142  False   0.16        1.0     101.53869              1.0           Yes

    False Positive False Negative True Negative Promote Demote
0               No             No           Yes      No     No
1               No             No            No      No     No
2               No             No           Yes      No     No
3               No             No           Yes      No     No
4               No             No           Yes      No     No
..             ...            ...           ...     ...    ...
138             No             No           Yes      No     No
139             No             No           Yes      No     No
140             No             No            No      No     No
141             No             No           Yes      No     No
142             No             No            No      No     No

[143 rows x 19 columns]
-------------------------------------------------------
Learned Model Predictions on Testing Data Set
-------------------------------------------------------
       ID  RefractiveIndex  Sodium    Mag  Alum  Silicon      K  Calcium  \
0     2.0          1.51761   13.89    3.6  1.36    72.73   0.48     7.83
1     3.0          1.51618   13.53   3.55  1.54    72.99   0.39     7.78
2     7.0          1.51743   13.30    3.6  1.14    73.09   0.58     8.17
3    13.0          1.51589   12.88   3.43   1.4    73.28   0.69     8.05
4    14.0          1.51748   12.86   3.56  1.27    73.21   0.54     8.38
..    ...              ...     ...    ...   ...      ...    ...      ...
65  205.0          1.51617   14.95  False  2.27    73.30  False     8.71
66  207.0          1.51645   14.94  False  1.87    73.11  False     8.67
67  211.0          1.51685   14.92  False  1.99    73.06  False     8.40
68  213.0          1.51651   14.38  False  1.94    73.61  False     8.48
69  214.0          1.51711   14.23  False  2.08    73.36  False     8.62

   Barium   Iron  GlassType  Weighted Sum  Predicted Class True Positive  \
0   False  False        1.0     101.40761              1.0           Yes
1   False  False        1.0     101.29618              1.0           Yes
2   False  False        1.0     101.39743              1.0           Yes
3   False   0.24        1.0     101.48589              1.0           Yes
4   False   0.17        1.0     101.50748              1.0           Yes
..    ...    ...        ...           ...              ...           ...
65   0.67  False        7.0     101.41617              1.0            No
66   1.38  False        7.0     101.48645              1.0            No
67   1.59  False        7.0     101.47685              1.0            No
68   1.57  False        7.0     101.49651              1.0            No
69   1.67  False        7.0     101.47711              1.0            No

   False Positive False Negative True Negative
0              No             No            No
1              No             No            No
2              No             No            No
3              No             No            No
4              No             No            No
..            ...            ...           ...
65             No             No           Yes
66             No             No           Yes
67             No             No           Yes
68             No             No           Yes
69             No             No           Yes

[70 rows x 17 columns]


-------------------------------------------------------
Winnow2 Summary Statistics (Testing)
-------------------------------------------------------
Data Set : Glass.Data

Number of Test Instances : 70
True Positives : 21
False Positives : 0
False Negatives : 0
True Negatives : 49
Accuracy : 100.0%

#### Iris

In [32]:
DataPath = "Iris.Data"
TrainWeightFile = "Winnow/Iris/TrainWeightFile.txt"
TrainOutFile = "Winnow/Iris/TrainOutFile.txt"
TestStatsFile = "Winnow/Iris/TestStatsFile.txt"
TestOutFile = "Winnow/Iris/TestOutFile.txt"
Winnow2.Winnow(Iris, DataPath, TrainWeightFile, TrainOutFile, TestStatsFile, TestOutFile)

----------------------------------------------------------
 Winnow2 Results
----------------------------------------------------------
Data Set : Iris.Data


----------------------------
Weights of the Learned Model
----------------------------
Sepal_W : 1.0
Petal_L : 1.0
Petal_W : 1.0


-----------
Constants
-----------
THETA = 0.5
ALPHA = 2.0

-------------------------------------------------------
Learned Model Runs of the Training Data Set (in binary)
-------------------------------------------------------
[[6.7 3.1 5.6 ... 0.  0.  0. ]
 [4.9 3.1 1.5 ... 0.  0.  1. ]
 [6.6 3.  4.4 ... 1.  0.  0. ]
 ...
 [5.1 3.4 1.5 ... 0.  0.  1. ]
 [6.3 2.9 5.6 ... 0.  0.  0. ]
 [6.  2.2 4.  ... 1.  0.  0. ]]


-------------------------------------------------------
Learned Model Runs of the Training Data Set (readable)
-------------------------------------------------------
    Sepal_L  Sepal_W  Petal_L Petal_W  Class  Weighted Sum  Predicted Class  \
0       6.7      3.1      5.6     2.4    1.0          11.1              1.0
1       4.9      3.1      1.5     0.1    0.0           4.7              1.0
2       6.6      3.0      4.4     1.4    2.0           8.8              1.0
3       5.6      2.8      4.9       2    1.0           9.7              1.0
4       5.4      3.9      1.7     0.4    0.0           6.0              1.0
..      ...      ...      ...     ...    ...           ...              ...
95      6.7      3.3      5.7     2.1    1.0          11.1              1.0
96      5.8      2.7      4.1    True    2.0           7.8              1.0
97      5.1      3.4      1.5     0.2    0.0           5.1              1.0
98      6.3      2.9      5.6     1.8    1.0          10.3              1.0
99      6.0      2.2      4.0    True    2.0           7.2              1.0

   True Positive False Positive False Negative True Negative Promote Demote
0            Yes             No             No            No      No     No
1             No            Yes             No            No      No    Yes
2             No             No             No           Yes      No     No
3            Yes             No             No            No      No     No
4             No            Yes             No            No      No    Yes
..           ...            ...            ...           ...     ...    ...
95           Yes             No             No            No      No     No
96            No             No             No           Yes      No     No
97            No            Yes             No            No      No    Yes
98           Yes             No             No            No      No     No
99            No             No             No           Yes      No     No

[100 rows x 13 columns]
-------------------------------------------------------
Learned Model Predictions on Testing Data Set
-------------------------------------------------------
    Sepal_L  Sepal_W Petal_L Petal_W  Class  Weighted Sum  Predicted Class  \
0       4.9      3.0     1.4     0.2    0.0           4.6              1.0
1       4.7      3.2     1.3     0.2    0.0           4.7              1.0
2       4.6      3.4     1.4     0.3    0.0           5.1              1.0
3       4.8      3.0     1.4     0.1    0.0           4.5              1.0
4       4.3      3.0     1.1     0.1    0.0           4.2              1.0
5       5.7      3.8     1.7     0.3    0.0           5.8              1.0
6       5.4      3.4     1.7     0.2    0.0           5.3              1.0
7       5.1      3.7     1.5     0.4    0.0           5.6              1.0
8       4.6      3.6    True     0.2    0.0           4.8              1.0
9       5.1      3.3     1.7     0.5    0.0           5.5              1.0
10      4.8      3.4     1.9     0.2    0.0           5.5              1.0
11      5.2      3.5     1.5     0.2    0.0           5.2              1.0
12      5.2      3.4     1.4     0.2    0.0           5.0              1.0
13      4.9      3.1     1.5     0.1    0.0           4.7              1.0
14      5.5      3.5     1.3     0.2    0.0           5.0              1.0
15      5.0      3.5     1.3     0.3    0.0           5.1              1.0
16      4.4      3.2     1.3     0.2    0.0           4.7              1.0
17      4.8      3.0     1.4     0.3    0.0           4.7              1.0
18      5.3      3.7     1.5     0.2    0.0           5.4              1.0
19      6.4      3.2     4.5     1.5    2.0           9.2              1.0
20      6.5      2.8     4.6     1.5    2.0           8.9              1.0
21      6.3      3.3     4.7     1.6    2.0           9.6              1.0
22      5.0      2.0     3.5    True    2.0           6.5              1.0
23      6.1      2.9     4.7     1.4    2.0           9.0              1.0
24      5.6      2.5     3.9     1.1    2.0           7.5              1.0
25      6.4      2.9     4.3     1.3    2.0           8.5              1.0
26      6.8      2.8     4.8     1.4    2.0           9.0              1.0
27      6.7      3.0       5     1.7    2.0           9.7              1.0
28      6.0      2.9     4.5     1.5    2.0           8.9              1.0
29      5.5      2.4     3.8     1.1    2.0           7.3              1.0
30      5.5      2.5       4     1.3    2.0           7.8              1.0
31      5.8      2.6       4     1.2    2.0           7.8              1.0
32      5.6      2.7     4.2     1.3    2.0           8.2              1.0
33      5.7      2.9     4.2     1.3    2.0           8.4              1.0
34      6.2      2.9     4.3     1.3    2.0           8.5              1.0
35      6.3      3.3       6     2.5    1.0          11.8              1.0
36      6.7      2.5     5.8     1.8    1.0          10.1              1.0
37      5.8      2.8     5.1     2.4    1.0          10.3              1.0
38      6.4      3.2     5.3     2.3    1.0          10.8              1.0
39      7.7      2.8     6.7       2    1.0          11.5              1.0
40      7.2      3.0     5.8     1.6    1.0          10.4              1.0
41      7.4      2.8     6.1     1.9    1.0          10.8              1.0
42      7.9      3.8     6.4       2    1.0          12.2              1.0
43      6.1      2.6     5.6     1.4    1.0           9.6              1.0
44      6.9      3.1     5.4     2.1    1.0          10.6              1.0
45      6.9      3.1     5.1     2.3    1.0          10.5              1.0
46      6.8      3.2     5.9     2.3    1.0          11.4              1.0
47      6.2      3.4     5.4     2.3    1.0          11.1              1.0
48      5.9      3.0     5.1     1.8    1.0           9.9              1.0

   True Positive False Positive False Negative True Negative
0             No            Yes             No            No
1             No            Yes             No            No
2             No            Yes             No            No
3             No            Yes             No            No
4             No            Yes             No            No
5             No            Yes             No            No
6             No            Yes             No            No
7             No            Yes             No            No
8             No            Yes             No            No
9             No            Yes             No            No
10            No            Yes             No            No
11            No            Yes             No            No
12            No            Yes             No            No
13            No            Yes             No            No
14            No            Yes             No            No
15            No            Yes             No            No
16            No            Yes             No            No
17            No            Yes             No            No
18            No            Yes             No            No
19            No             No             No           Yes
20            No             No             No           Yes
21            No             No             No           Yes
22            No             No             No           Yes
23            No             No             No           Yes
24            No             No             No           Yes
25            No             No             No           Yes
26            No             No             No           Yes
27            No             No             No           Yes
28            No             No             No           Yes
29            No             No             No           Yes
30            No             No             No           Yes
31            No             No             No           Yes
32            No             No             No           Yes
33            No             No             No           Yes
34            No             No             No           Yes
35           Yes             No             No            No
36           Yes             No             No            No
37           Yes             No             No            No
38           Yes             No             No            No
39           Yes             No             No            No
40           Yes             No             No            No
41           Yes             No             No            No
42           Yes             No             No            No
43           Yes             No             No            No
44           Yes             No             No            No
45           Yes             No             No            No
46           Yes             No             No            No
47           Yes             No             No            No
48           Yes             No             No            No


-------------------------------------------------------
Winnow2 Summary Statistics (Testing)
-------------------------------------------------------
Data Set : Iris.Data

Number of Test Instances : 49
True Positives : 14
False Positives : 19
False Negatives : 0
True Negatives : 16
Accuracy : 61.224489795918366%

#### Soybean

In [33]:
DataPath = "SoyBean.Data"
TrainWeightFile = "Winnow/SoyBean/TrainWeightFile.txt"
TrainOutFile = "Winnow/SoyBean/TrainOutFile.txt"
TestStatsFile = "Winnow/SoyBean/TestStatsFile.txt"
TestOutFile = "Winnow/SoyBean/TestOutFile.txt"
Winnow2.Winnow(SoyBean, DataPath, TrainWeightFile, TrainOutFile, TestStatsFile, TestOutFile)

----------------------------------------------------------
 Winnow2 Results
----------------------------------------------------------
Data Set : SoyBean.Data


----------------------------
Weights of the Learned Model
----------------------------
plantstand : 1.0
precip : 1.0
temp : 1.0
hail : 1.0
crophist : 1.0
areadamaged : 1.0
severity : 1.0
seedtmt : 1.0
germination : 1.0
plantgrowth : 1.0
leaves : 1.0
leafspotsmarg : 1.0
leafspotsize : 1.0
stem : 1.0
lodging : 1.0
stemcankers : 1.0
cankerlesion : 1.0
fruitingbodies : 1.0
externaldecay : 1.0
mycelium : 1.0
intdiscolor : 1.0
sclerotia : 1.0
fruitpods : 1.0
fruitspots : 1.0
roots : 1.0


-----------
Constants
-----------
THETA = 0.5
ALPHA = 2.0

-------------------------------------------------------
Learned Model Runs of the Training Data Set (in binary)
-------------------------------------------------------
[[3. 0. 0. ... 1. 0. 0.]
 [3. 0. 2. ... 1. 0. 0.]
 [4. 0. 0. ... 1. 0. 0.]
 ...
 [6. 0. 2. ... 0. 0. 0.]
 [6. 0. 0. ... 1. 0. 0.]
 [5. 0. 2. ... 0. 0. 0.]]


-------------------------------------------------------
Learned Model Runs of the Training Data Set (readable)
-------------------------------------------------------
    date plantstand precip   temp   hail crophist areadamaged severity  \
0    3.0      False  False      2   True    False           2     True
1    3.0      False      2  False   True        3        True        2
2    4.0      False  False   True  False        2           3     True
3    1.0       True      2   True  False    False        True        2
4    5.0      False  False      2  False        3           2     True
5    4.0      False      2  False   True    False        True        2
6    0.0       True      2  False  False    False        True     True
7    0.0       True      2  False  False     True        True     True
8    0.0       True      2  False  False    False        True     True
9    3.0       True      2  False  False     True        True        2
10   3.0      False      2   True  False     True       False        2
11   1.0       True      2  False  False    False        True        2
12   4.0      False      2   True  False        3       False        2
13   5.0      False  False      2   True        2           2     True
14   2.0       True      2  False  False        2        True     True
15   0.0       True   True   True  False     True        True     True
16   1.0       True      2   True   True        2           3     True
17   6.0      False  False      2  False     True           3     True
18   1.0       True      2  False  False        3        True     True
19   0.0       True      2   True   True     True        True     True
20   4.0      False  False   True   True     True           3     True
21   3.0       True   True  False  False        2        True        2
22   2.0       True      2   True   True     True        True        2
23   3.0      False  False   True  False     True           2     True
24   6.0      False      2   True  False        3       False     True
25   2.0       True      2  False  False        3        True        2
26   2.0       True      2  False  False        3        True        2
27   0.0       True      2  False  False     True        True        2
28   6.0      False      2   True  False     True       False     True
29   6.0      False  False   True   True        3           3     True
30   5.0      False      2   True  False        3        True     True

   seedtmt germination  ...  roots Distrubution  Weighted Sum  \
0    False        True  ...  False          2.0          24.0
1    False        True  ...  False          3.0          28.0
2     True        True  ...  False          2.0          26.0
3     True        True  ...   True          4.0          28.0
4    False           2  ...  False          2.0          27.0
5    False           2  ...  False          3.0          27.0
6     True           2  ...  False          3.0          24.0
7     True        True  ...  False          3.0          25.0
8    False        True  ...   True          3.0          23.0
9     True       False  ...   True          4.0          27.0
10    True           2  ...  False          1.0          25.0
11    True       False  ...   True          4.0          26.0
12   False           2  ...  False          1.0          27.0
13   False           2  ...  False          2.0          28.0
14   False           2  ...  False          3.0          26.0
15   False       False  ...   True          4.0          24.0
16    True        True  ...   True          4.0          33.0
17    True       False  ...  False          2.0          25.0
18    True           2  ...   True          4.0          30.0
19   False       False  ...   True          4.0          27.0
20    True        True  ...  False          2.0          27.0
21    True           2  ...   True          4.0          29.0
22   False           2  ...   True          4.0          30.0
23   False       False  ...  False          2.0          22.0
24    True        True  ...  False          1.0          26.0
25   False           2  ...  False          3.0          28.0
26   False        True  ...  False          3.0          26.0
27    True           2  ...  False          3.0          26.0
28   False           2  ...  False          1.0          24.0
29    True       False  ...  False          2.0          27.0
30    True           2  ...  False          1.0          28.0

    Predicted Class True Positive False Positive False Negative True Negative  \
0               1.0            No             No             No           Yes
1               1.0            No             No             No           Yes
2               1.0            No             No             No           Yes
3               1.0            No             No             No           Yes
4               1.0            No             No             No           Yes
5               1.0            No             No             No           Yes
6               1.0            No             No             No           Yes
7               1.0            No             No             No           Yes
8               1.0            No             No             No           Yes
9               1.0            No             No             No           Yes
10              1.0           Yes             No             No            No
11              1.0            No             No             No           Yes
12              1.0           Yes             No             No            No
13              1.0            No             No             No           Yes
14              1.0            No             No             No           Yes
15              1.0            No             No             No           Yes
16              1.0            No             No             No           Yes
17              1.0            No             No             No           Yes
18              1.0            No             No             No           Yes
19              1.0            No             No             No           Yes
20              1.0            No             No             No           Yes
21              1.0            No             No             No           Yes
22              1.0            No             No             No           Yes
23              1.0            No             No             No           Yes
24              1.0           Yes             No             No            No
25              1.0            No             No             No           Yes
26              1.0            No             No             No           Yes
27              1.0            No             No             No           Yes
28              1.0           Yes             No             No            No
29              1.0            No             No             No           Yes
30              1.0           Yes             No             No            No

   Promote Demote
0       No     No
1       No     No
2       No     No
3       No     No
4       No     No
5       No     No
6       No     No
7       No     No
8       No     No
9       No     No
10      No     No
11      No     No
12      No     No
13      No     No
14      No     No
15      No     No
16      No     No
17      No     No
18      No     No
19      No     No
20      No     No
21      No     No
22      No     No
23      No     No
24      No     No
25      No     No
26      No     No
27      No     No
28      No     No
29      No     No
30      No     No

[31 rows x 35 columns]

-------------------------------------------------------
Learned Model Predictions on Testing Data Set
-------------------------------------------------------
    date plantstand precip   temp   hail crophist areadamaged severity  \
0    3.0      False      2   True  False        2       False        2
1    6.0      False      2   True  False     True        True     True
2    5.0      False      2   True  False        2       False     True
3    3.0      False      2   True  False        2        True     True
4    6.0      False  False      2   True    False           2     True
5    5.0      False  False      2   True        3           3     True
6    0.0       True      2  False  False        2        True     True
7    2.0       True      2   True   True        3        True        2
8    0.0       True      2   True  False        3        True     True
9    2.0       True      2  False  False     True        True        2
10   3.0       True      2  False  False        2        True        2
11   1.0       True      2   True   True        3        True        2
12   2.0       True   True  False  False        3        True        2
13   0.0       True   True   True   True        2        True        2
14   0.0       True      2   True  False        3        True     True

   seedtmt germination  ... fruitpods fruitspots  roots  Distrubution  \
0     True        True  ...     False        4.0  False           1.0
1    False       False  ...     False        4.0  False           1.0
2     True       False  ...     False        4.0  False           1.0
3    False        True  ...     False        4.0  False           1.0
4    False       False  ...     False        4.0  False           2.0
5     True           2  ...     False        4.0  False           2.0
6     True        True  ...         3        4.0  False           3.0
7     True           2  ...         3        4.0   True           4.0
8    False       False  ...         3        4.0   True           4.0
9    False       False  ...         3        4.0   True           4.0
10    True        True  ...         3        4.0   True           4.0
11   False        True  ...         3        4.0   True           4.0
12   False           2  ...         3        4.0   True           4.0
13    True       False  ...         3        4.0   True           4.0
14   False           2  ...         3        4.0   True           4.0

   Weighted Sum Predicted Class True Positive False Positive False Negative  \
0          25.0             1.0           Yes             No             No
1          24.0             1.0           Yes             No             No
2          25.0             1.0           Yes             No             No
3          25.0             1.0           Yes             No             No
4          24.0             1.0            No             No             No
5          30.0             1.0            No             No             No
6          25.0             1.0            No             No             No
7          34.0             1.0            No             No             No
8          27.0             1.0            No             No             No
9          25.0             1.0            No             No             No
10         29.0             1.0            No             No             No
11         32.0             1.0            No             No             No
12         28.0             1.0            No             No             No
13         31.0             1.0            No             No             No
14         29.0             1.0            No             No             No

   True Negative
0             No
1             No
2             No
3             No
4            Yes
5            Yes
6            Yes
7            Yes
8            Yes
9            Yes
10           Yes
11           Yes
12           Yes
13           Yes
14           Yes

[15 rows x 33 columns]


-------------------------------------------------------
Winnow2 Summary Statistics (Testing)
-------------------------------------------------------
Data Set : SoyBean.Data

Number of Test Instances : 15
True Positives : 4
False Positives : 0
False Negatives : 0
True Negatives : 11
Accuracy : 100.0%

#### Vote

In [34]:
DataPath = "Vote.Data"
TrainWeightFile = "Winnow/Vote/TrainWeightFile.txt"
TrainOutFile = "Winnow/Vote/TrainOutFile.txt"
TestStatsFile = "Winnow/Vote/TestStatsFile.txt"
TestOutFile = "Winnow/Vote/TestOutFile.txt"
Winnow2.Winnow(Vote, DataPath, TrainWeightFile, TrainOutFile, TestStatsFile, TestOutFile)

----------------------------------------------------------
 Winnow2 Results
----------------------------------------------------------
Data Set : Vote.Data


----------------------------
Weights of the Learned Model
----------------------------
Handicap : 0.0625
Water : 0.0078125
Adoption : 0.5
Physician : 0.03125
SalvadorAid : 0.03125
ReligionInSchool : 0.015625
SatelitteTestBan : 0.5
NicaraguanAid : 0.5
Missile : 0.5
Immigration : 0.0625
CorpCutBack : 0.015625
Education : 0.125
Sue : 0.00390625
Crime : 0.0625
DutyFreeExport : 0.125


-----------
Constants
-----------
THETA = 0.5
ALPHA = 2.0

-------------------------------------------------------
Learned Model Runs of the Training Data Set (in binary)
-------------------------------------------------------
[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


-------------------------------------------------------
Learned Model Runs of the Training Data Set (readable)
-------------------------------------------------------
     Class Handicap  Water Adoption Physician SalvadorAid ReligionInSchool  \
0      0.0    False   True     True      True        True             True
1      0.0     True   True     True     False       False            False
2      1.0    False  False    False      True        True             True
3      1.0    False  False    False      True        True             True
4      0.0    False  False     True     False       False            False
..     ...      ...    ...      ...       ...         ...              ...
150    1.0     True  False    False      True        True             True
151    1.0    False   True    False      True        True             True
152    0.0    False   True     True     False       False            False
153    0.0    False   True     True     False        True             True
154    0.0    False   True     True     False       False             True

    SatelitteTestBan NicaraguanAid Missile  ... DutyFreeExport ExportAdmin  \
0              False          True    True  ...          False         1.0
1              False          True    True  ...           True         1.0
2              False         False   False  ...          False         0.0
3              False         False   False  ...          False         1.0
4               True          True    True  ...           True         1.0
..               ...           ...     ...  ...            ...         ...
150            False         False   False  ...          False         0.0
151            False         False   False  ...          False         0.0
152             True          True    True  ...           True         1.0
153             True         False    True  ...          False         1.0
154            False          True    True  ...           True         1.0

    Weighted Sum Predicted Class True Positive False Positive  False Negative  \
0      12.000000             1.0           Yes             No              No
1       7.000000             1.0           Yes             No              No
2       7.000000             1.0            No            Yes              No
3       3.500000             1.0           Yes             No              No
4       5.000000             1.0           Yes             No              No
..           ...             ...           ...            ...             ...
150     0.789062             1.0            No            Yes              No
151     0.339844             0.0            No             No              No
152     2.210938             1.0           Yes             No              No
153     1.699219             1.0           Yes             No              No
154     1.667969             1.0           Yes             No              No

     True Negative  Promote Demote
0               No       No     No
1               No       No     No
2               No       No    Yes
3               No       No     No
4               No       No     No
..             ...      ...    ...
150             No       No    Yes
151            Yes       No     No
152             No       No     No
153             No       No     No
154             No       No     No

[155 rows x 25 columns]
-------------------------------------------------------
Learned Model Predictions on Testing Data Set
-------------------------------------------------------
    Class Handicap  Water Adoption Physician SalvadorAid ReligionInSchool  \
0     0.0    False   True     True     False        True             True
1     1.0    False   True    False      True        True             True
2     0.0     True  False     True     False       False            False
3     1.0    False   True    False      True        True             True
4     0.0     True   True     True     False       False            False
..    ...      ...    ...      ...       ...         ...              ...
72    0.0     True   True     True     False       False            False
73    0.0     True  False     True     False       False            False
74    1.0    False  False    False      True        True             True
75    1.0    False  False     True      True        True             True
76    0.0    False  False     True     False       False            False

   SatelitteTestBan NicaraguanAid Missile  ...    Sue  Crime DutyFreeExport  \
0             False         False   False  ...   True   True           True
1             False         False   False  ...   True   True          False
2              True          True    True  ...  False  False           True
3             False         False   False  ...   True   True          False
4              True          True    True  ...  False  False           True
..              ...           ...     ...  ...    ...    ...            ...
72             True          True    True  ...   True  False          False
73             True          True    True  ...  False  False           True
74             True          True   False  ...   True   True          False
75            False         False    True  ...   True   True          False
76             True          True    True  ...  False  False          False

   ExportAdmin Weighted Sum Predicted Class  True Positive  False Positive  \
0          1.0     0.746094             1.0            Yes              No
1          1.0     0.277344             0.0             No              No
2          1.0     2.203125             1.0            Yes              No
3          1.0     0.277344             0.0             No              No
4          1.0     2.195312             1.0            Yes              No
..         ...          ...             ...            ...             ...
72         1.0     2.152344             1.0            Yes              No
73         1.0     2.250000             1.0            Yes              No
74         1.0     1.332031             1.0            Yes              No
75         1.0     1.332031             1.0            Yes              No
76         1.0     2.062500             1.0            Yes              No

    False Negative True Negative
0               No            No
1              Yes            No
2               No            No
3              Yes            No
4               No            No
..             ...           ...
72              No            No
73              No            No
74              No            No
75              No            No
76              No            No

[77 rows x 23 columns]


-------------------------------------------------------
Winnow2 Summary Statistics (Testing)
-------------------------------------------------------
Data Set : Vote.Data

Number of Test Instances : 77
True Positives : 54
False Positives : 1
False Negatives : 10
True Negatives : 12
Accuracy : 85.71428571428571%

### Bayes

In [35]:
import BayesMain

#### Breast Cancer

In [36]:
Data = BreastCancer
DataPath = "breast_cancer.txt"
TraceRunFile = "Bayes/BreastCancer/TraceFile.txt"
StatsFile = "Bayes/BreastCancer/TestStats.txt"
BayesMain.BayesMain(Data, DataPath, TraceRunFile, StatsFile)

Naive Bayes Program!


Running Experiment 1 ...

Accuracy:
96.35036496350365%

Classifications:
    Sample_code_number Clump_Thickness Uniformity_CellSize  \
0              1266154               8                   7
1              1350423               5                  10
2               303213              10                   4
3               492268              10                   4
4              1371026               5                  10
..                 ...             ...                 ...
132            1171578               3                   1
133            1066979               5                   1
134            1229929               1                   1
135            1070935               1                   1
136            1268313               5                   1

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                      8                2           4          2
1                     10                8           5          5
2                      4               10           6         10
3                      6                1           2         10
4                     10               10           4         10
..                   ...              ...         ...        ...
132                    1                1           2          1
133                    1                1           2          1
134                    1                1           2          1
135                    3                1           2          1
136                    1                3           2          1

    BlandChromatin NormalNucleoli Mitoses Class  Predicted Class  \
0                5             10       1     0              0.0
1                7             10       1     0              0.0
2                5              5       1     0              0.0
3                5              3       1     0              0.0
4                5              6       3     0              0.0
..             ...            ...     ...   ...              ...
132              1              1       1     1              1.0
133              2              1       1     1              1.0
134              2              1       1     1              1.0
135              1              1       1     1              1.0
136              1              1       1     1              1.0

    Prediction Correct?
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
..                  ...
132                 Yes
133                 Yes
134                 Yes
135                 Yes
136                 Yes

[137 rows x 13 columns]

Learned Model (Likelihood Table):
                           0
Clump_Thickness70   0.109948
Clump_Thickness100  0.314136
Clump_Thickness50   0.162304
Clump_Thickness80   0.157068
Clump_Thickness90   0.073298
...                      ...
Mitoses101          0.000000
Mitoses21           0.019774
Mitoses81           0.002825
Mitoses71           0.002825
Mitoses51           0.002825

[178 rows x 1 columns]

Number of Test Instances:
137


Running Experiment 2 ...

Accuracy:
96.35036496350365%

Classifications:
    Sample_code_number Clump_Thickness Uniformity_CellSize  \
0               667204               7                   8
1              1296572              10                   9
2              1108449               5                   3
3              1216694              10                   8
4               730881               7                   6
..                 ...             ...                 ...
132            1290203               3                   1
133            1182404               4                   1
134            1296025               4                   1
135            1321942               5                   1
136            1033078               4                   2

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                      7                6           4          3
1                      8                7           6          4
2                      3                4           2          4
3                      8                4          10         10
4                      3                2           5         10
..                   ...              ...         ...        ...
132                    1                1           2          1
133                    1                1           2          1
134                    2                1           2          1
135                    1                1           2          1
136                    1                1           2          1

    BlandChromatin NormalNucleoli Mitoses Class  Predicted Class  \
0                8              8       4     0              0.0
1                7             10       3     0              0.0
2                3              4       1     0              0.0
3                8              1       1     0              0.0
4                7              4       6     0              0.0
..             ...            ...     ...   ...              ...
132              2              1       1     1              1.0
133              2              1       1     1              1.0
134              1              1       1     1              1.0
135              3              1       1     1              1.0
136              2              1       1     1              1.0

    Prediction Correct?
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
..                  ...
132                 Yes
133                 Yes
134                 Yes
135                 Yes
136                 Yes

[137 rows x 13 columns]

Learned Model (Likelihood Table):
                           0
Clump_Thickness80   0.162304
Clump_Thickness50   0.198953
Clump_Thickness100  0.282723
Clump_Thickness30   0.057592
Clump_Thickness40   0.052356
...                      ...
Mitoses41           0.000000
Mitoses71           0.002825
Mitoses81           0.002825
Mitoses61           0.000000
Mitoses51           0.002825

[178 rows x 1 columns]

Number of Test Instances:
137


Running Experiment 3 ...

Accuracy:
96.35036496350365%

Classifications:
    Sample_code_number Clump_Thickness Uniformity_CellSize  \
0              1257470              10                   6
1              1166630               7                   5
2               527363               8                  10
3               695091               5                  10
4               144888               8                  10
..                 ...             ...                 ...
132            1321348               2                   1
133             558538               4                   1
134            1213375               8                   4
135            1213383               5                   1
136             769612               4                   1

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                      5                8           5         10
1                      6               10           5         10
2                     10               10           8         10
3                     10                5           4          5
4                     10                8           5         10
..                   ...              ...         ...        ...
132                    1                1           2          1
133                    3                3           2          1
134                    4                5           4          7
135                    1                4           2          1
136                    1                1           2          1

    BlandChromatin NormalNucleoli Mitoses Class  Predicted Class  \
0                8              6       1     0              0.0
1                7              9       4     0              0.0
2               10              7       3     0              0.0
3                4              4       1     0              0.0
4                7              8       1     0              0.0
..             ...            ...     ...   ...              ...
132              2              1       1     1              1.0
133              1              1       1     1              1.0
134              7              8       2     1              0.0
135              3              1       1     1              1.0
136              1              1       1     1              1.0

    Prediction Correct?
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
..                  ...
132                 Yes
133                 Yes
134                  No
135                 Yes
136                 Yes

[137 rows x 13 columns]

Learned Model (Likelihood Table):
                           0
Clump_Thickness80   0.162304
Clump_Thickness50   0.183246
Clump_Thickness100  0.303665
Clump_Thickness30   0.047120
Clump_Thickness40   0.057592
...                      ...
Mitoses41           0.000000
Mitoses71           0.000000
Mitoses61           0.000000
Mitoses81           0.002825
Mitoses51           0.002825

[178 rows x 1 columns]

Number of Test Instances:
137


Running Experiment 4 ...

Accuracy:
95.58823529411765%

Classifications:
    Sample_code_number Clump_Thickness Uniformity_CellSize  \
0              1241559              10                   8
1              1331412               5                   7
2              1103608              10                  10
3              1352663               5                   4
4              1125035               9                   4
..                 ...             ...                 ...
131            1277018               2                   1
132            1190485               1                   1
133             466906               1                   1
134            1074610               2                   1
135            1320077               1                   1

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                      8                2           8         10
1                     10               10           5         10
2                     10                4           8          1
3                      6                8           4          1
4                      5               10           6         10
..                   ...              ...         ...        ...
131                    1                1           2          1
132                    1                1           2          1
133                    1                1           2          1
134                    1                2           2          1
135                    1                1           1          1

    BlandChromatin NormalNucleoli Mitoses Class  Predicted Class  \
0                4              8      10     0              0.0
1               10             10       1     0              0.0
2                8             10       1     0              0.0
3                8             10       1     0              0.0
4                4              8       1     0              0.0
..             ...            ...     ...   ...              ...
131              3              1       1     1              1.0
132              1              1       1     1              1.0
133              1              1       1     1              1.0
134              3              1       1     1              1.0
135              2              1       1     1              1.0

    Prediction Correct?
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
..                  ...
131                 Yes
132                 Yes
133                 Yes
134                 Yes
135                 Yes

[136 rows x 13 columns]

Learned Model (Likelihood Table):
                           0
Clump_Thickness80   0.167539
Clump_Thickness50   0.188482
Clump_Thickness100  0.272251
Clump_Thickness30   0.052356
Clump_Thickness40   0.052356
...                      ...
Mitoses41           0.000000
Mitoses71           0.002817
Mitoses61           0.000000
Mitoses81           0.002817
Mitoses51           0.002817

[178 rows x 1 columns]

Number of Test Instances:
136


Running Experiment 5 ...

Accuracy:
97.03703703703704%

Classifications:
    Sample_code_number Clump_Thickness Uniformity_CellSize  \
0              1168736              10                  10
1              1100524               6                  10
2              1147699               3                   5
3               145447               8                   4
4              1211202               7                   5
..                 ...             ...                 ...
130             566346               3                   1
131             837082               2                   1
132            1156017               3                   1
133            1178580               5                   1
134            1313982               4                   3

    Uniformity_CellShape MarginalAdhesion SE_CellSize BareNuclei  \
0                     10               10          10          1
1                     10                2           8         10
2                      7                8           8          9
3                      4                1           2          9
4                     10               10          10         10
..                   ...              ...         ...        ...
130                    1                1           2          1
131                    1                1           2          1
132                    1                1           2          1
133                    3                1           2          1
134                    1                1           2          1

    BlandChromatin NormalNucleoli Mitoses Class  Predicted Class  \
0                8              8       8     0              0.0
1                7              3       3     0              0.0
2                7             10       7     0              0.0
3                3              3       1     0              0.0
4                4             10       3     0              0.0
..             ...            ...     ...   ...              ...
130              2              3       1     1              1.0
131              3              1       1     1              1.0
132              2              1       1     1              1.0
133              2              1       1     1              1.0
134              4              8       1     1              1.0

    Prediction Correct?
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
..                  ...
130                 Yes
131                 Yes
132                 Yes
133                 Yes
134                 Yes

[135 rows x 13 columns]

Learned Model (Likelihood Table):
                           0
Clump_Thickness80   0.187500
Clump_Thickness50   0.208333
Clump_Thickness100  0.270833
Clump_Thickness30   0.057292
Clump_Thickness40   0.046875
...                      ...
Mitoses41           0.000000
Mitoses71           0.002817
Mitoses61           0.000000
Mitoses81           0.000000
Mitoses51           0.000000

[178 rows x 1 columns]

Number of Test Instances:
135

Experiments Completed.


----------------------------------------------------------
Naive Bayes Summary Statistics
----------------------------------------------------------
Data Set : breast_cancer.txt


Accuracy Statistics for All 5 Experiments:
[0.96350365 0.96350365 0.96350365 0.95588235 0.97037037]


Classification Accuracy : 96.33527344433313%

#### Glass

In [37]:
Data = Glass
DataPath = "Glass.txt"
TraceRunFile = "Bayes/Glass/TraceFile.txt"
StatsFile = "Bayes/Glass/TestStats.txt"
BayesMain.BayesMain(Data, DataPath, TraceRunFile, StatsFile)

Naive Bayes Program!


Running Experiment 1 ...

Accuracy:
31.11111111111111%

Classifications:
       ID  RefractiveIndex  Sodium   Mag  Alum  Silicon     K  Calcium  \
0    30.0          1.51784   13.08  3.49  1.28    72.86  0.60     8.49
1    61.0          1.51905   13.60  3.62  1.11    72.64  0.14     8.76
2    31.0          1.51768   12.65  3.56  1.30    73.08  0.61     8.69
3    41.0          1.51793   12.79  3.50  1.12    73.03  0.64     8.77
4    46.0          1.51900   13.49  3.48  1.35    71.95  0.55     9.00
5    17.0          1.51784   12.68  3.67  1.16    73.11  0.61     8.70
6    39.0          1.52213   14.21  3.82  0.47    71.77  0.11     9.57
7    25.0          1.51720   13.38  3.50  1.15    72.85  0.50     8.43
8    13.0          1.51589   12.88  3.43  1.40    73.28  0.69     8.05
9    67.0          1.52152   13.05  3.65  0.87    72.22  0.19     9.85
10   26.0          1.51764   12.98  3.54  1.21    73.00  0.65     8.53
11   70.0          1.52300   13.31  3.58  0.82    71.99  0.12    10.17
12   40.0          1.52213   14.21  3.82  0.47    71.77  0.11     9.57
13    2.0          1.51761   13.89  3.60  1.36    72.73  0.48     7.83
14  124.0          1.51707   13.48  3.48  1.71    72.52  0.62     7.99
15  103.0          1.51820   12.62  2.76  0.83    73.81  0.35     9.42
16   77.0          1.51645   13.44  3.61  1.54    72.39  0.66     8.03
17  127.0          1.51667   12.94  3.61  1.26    72.75  0.56     8.60
18  122.0          1.51663   12.93  3.54  1.62    72.96  0.64     8.03
19  102.0          1.51730   12.35  2.72  1.63    72.87  0.70     9.23
20  123.0          1.51687   13.23  3.54  1.48    72.84  0.56     8.10
21   91.0          1.51841   12.93  3.74  1.11    72.28  0.64     8.96
22   85.0          1.51409   14.25  3.09  2.08    72.28  1.10     7.08
23  114.0          1.51892   13.46  3.83  1.26    72.55  0.57     8.21
24  129.0          1.52068   13.55  2.09  1.67    72.18  0.53     9.57
25   96.0          1.51860   13.36  3.43  1.43    72.26  0.51     8.60
26   76.0          1.51590   13.02  3.58  1.51    73.12  0.69     7.96
27   71.0          1.51574   14.86  3.67  1.74    71.87  0.16     7.36
28  134.0          1.51800   13.71  3.93  1.54    71.81  0.54     8.21
29   79.0          1.51613   13.92  3.52  1.25    72.88  0.37     7.94
30  151.0          1.51665   13.14  3.45  1.76    72.48  0.60     8.38
31  159.0          1.51776   13.53  3.41  1.52    72.04  0.58     8.79
32  150.0          1.51643   12.16  3.52  1.35    72.89  0.57     8.53
33  154.0          1.51610   13.42  3.40  1.22    72.69  0.59     8.32
34  167.0          1.52151   11.03  1.71  1.56    73.44  0.58    11.62
35  175.0          1.52058   12.85  1.61  2.17    72.18  0.76     9.70
36  164.0          1.51514   14.01  2.68  3.50    69.89  1.68     5.87
37  183.0          1.51916   14.15  0.00  2.09    72.74  0.00    10.88
38  179.0          1.51829   14.46  2.24  1.62    72.38  0.00     9.26
39  188.0          1.52315   13.44  3.34  1.23    72.38  0.60     8.83
40  214.0          1.51711   14.23  0.00  2.08    73.36  0.00     8.62
41  202.0          1.51653   11.95  0.00  1.19    75.18  2.70     8.93
42  205.0          1.51617   14.95  0.00  2.27    73.30  0.00     8.71
43  204.0          1.51658   14.80  0.00  1.99    73.11  0.00     8.28
44  197.0          1.51556   13.87  0.00  2.54    73.23  0.14     9.41

    Barium  Iron  GlassType  Predicted Class Prediction Correct?
0     0.00  0.00        1.0              1.0                 Yes
1     0.00  0.00        1.0              1.0                 Yes
2     0.00  0.14        1.0              1.0                 Yes
3     0.00  0.00        1.0              1.0                 Yes
4     0.00  0.00        1.0              1.0                 Yes
5     0.00  0.00        1.0              1.0                 Yes
6     0.00  0.00        1.0              1.0                 Yes
7     0.00  0.00        1.0              1.0                 Yes
8     0.00  0.24        1.0              1.0                 Yes
9     0.00  0.17        1.0              1.0                 Yes
10    0.00  0.00        1.0              1.0                 Yes
11    0.00  0.03        1.0              1.0                 Yes
12    0.00  0.00        1.0              1.0                 Yes
13    0.00  0.00        1.0              1.0                 Yes
14    0.00  0.00        2.0              1.0                  No
15    0.00  0.20        2.0              1.0                  No
16    0.00  0.00        2.0              1.0                  No
17    0.00  0.00        2.0              1.0                  No
18    0.00  0.21        2.0              1.0                  No
19    0.00  0.00        2.0              1.0                  No
20    0.00  0.00        2.0              1.0                  No
21    0.00  0.22        2.0              1.0                  No
22    0.00  0.00        2.0              1.0                  No
23    0.00  0.14        2.0              1.0                  No
24    0.27  0.17        2.0              1.0                  No
25    0.00  0.00        2.0              1.0                  No
26    0.00  0.00        2.0              1.0                  No
27    0.00  0.12        2.0              1.0                  No
28    0.00  0.15        2.0              1.0                  No
29    0.00  0.14        2.0              1.0                  No
30    0.00  0.17        3.0              1.0                  No
31    0.00  0.00        3.0              1.0                  No
32    0.00  0.00        3.0              1.0                  No
33    0.00  0.00        3.0              1.0                  No
34    0.00  0.00        5.0              1.0                  No
35    0.24  0.51        5.0              1.0                  No
36    2.20  0.00        5.0              1.0                  No
37    0.00  0.00        6.0              1.0                  No
38    0.00  0.00        6.0              1.0                  No
39    0.00  0.00        7.0              1.0                  No
40    1.67  0.00        7.0              1.0                  No
41    0.00  0.00        7.0              1.0                  No
42    0.67  0.00        7.0              1.0                  No
43    1.71  0.00        7.0              1.0                  No
44    0.81  0.01        7.0              1.0                  No

Learned Model (Likelihood Table):
                                        0
RefractiveIndex1.519261.0             1.0
RefractiveIndex1.517831.0             1.0
RefractiveIndex1.51761000000000011.0  1.0
RefractiveIndex1.518371.0             1.0
RefractiveIndex1.517631.0             1.0
...                                   ...
Iron0.087.0                           0.1
Iron0.317.0                           0.0
Iron0.347.0                           0.0
Iron0.37.0                            0.0
Iron0.077.0                           0.1

[4788 rows x 1 columns]

Number of Test Instances:
45


Running Experiment 2 ...

Accuracy:
31.818181818181817%

Classifications:
       ID  RefractiveIndex  Sodium   Mag  Alum  Silicon     K  Calcium  \
0    52.0          1.51926   13.20  3.33  1.28    72.36  0.60     9.14
1    35.0          1.51783   12.69  3.54  1.34    72.95  0.57     8.75
2    16.0          1.51761   12.81  3.54  1.23    73.24  0.58     8.39
3    54.0          1.51837   13.14  2.84  1.28    72.85  0.55     9.07
4    12.0          1.51763   12.80  3.66  1.27    73.01  0.60     8.56
5    58.0          1.51824   12.87  3.48  1.29    72.95  0.60     8.43
6    14.0          1.51748   12.86  3.56  1.27    73.21  0.54     8.38
7     7.0          1.51743   13.30  3.60  1.14    73.09  0.58     8.17
8    49.0          1.52223   13.21  3.77  0.79    71.99  0.13    10.02
9    32.0          1.51747   12.84  3.50  1.14    73.27  0.56     8.55
10   24.0          1.51751   12.81  3.57  1.35    73.02  0.62     8.59
11   62.0          1.51977   13.81  3.58  1.32    71.72  0.12     8.67
12   28.0          1.51721   12.87  3.48  1.33    73.04  0.56     8.43
13   29.0          1.51768   12.56  3.52  1.43    73.15  0.57     8.54
14   82.0          1.51593   13.25  3.45  1.43    73.17  0.61     7.86
15   99.0          1.51689   12.67  2.88  1.71    73.21  0.73     8.54
16  128.0          1.52081   13.78  2.28  1.43    71.99  0.49     9.85
17   73.0          1.51593   13.09  3.59  1.52    73.10  0.67     7.83
18  130.0          1.52020   13.98  1.35  1.63    71.76  0.39    10.56
19  146.0          1.51839   12.85  3.67  1.24    72.57  0.62     8.68
20  118.0          1.51708   13.72  3.68  1.81    72.06  0.64     7.88
21  126.0          1.51872   12.93  3.66  1.56    72.51  0.58     8.55
22  132.0          1.52614   13.70  0.00  1.36    71.24  0.19    13.44
23  145.0          1.51660   12.99  3.18  1.23    72.97  0.58     8.81
24  112.0          1.52739   11.02  0.00  0.75    73.08  0.00    14.96
25  143.0          1.51662   12.85  3.51  1.44    73.01  0.68     8.23
26  140.0          1.51674   12.87  3.56  1.64    73.14  0.65     7.99
27  115.0          1.51847   13.10  3.97  1.19    72.44  0.60     8.43
28  110.0          1.51818   13.72  0.00  0.56    74.45  0.00    10.99
29  155.0          1.51694   12.86  3.58  1.31    72.61  0.61     8.79
30  152.0          1.52127   14.32  3.90  0.83    71.50  0.00     9.49
31  160.0          1.51796   13.50  3.36  1.63    71.94  0.57     8.81
32  149.0          1.51670   13.24  3.57  1.38    72.70  0.56     8.44
33  171.0          1.52369   13.44  0.00  1.58    72.22  0.32    12.24
34  169.0          1.51666   12.86  0.00  1.83    73.88  0.97    10.17
35  168.0          1.51969   12.64  0.00  1.65    73.75  0.38    11.53
36  185.0          1.51115   17.38  0.00  0.34    75.41  0.00     6.65
37  180.0          1.51852   14.09  2.19  1.66    72.67  0.00     9.32
38  192.0          1.51602   14.85  0.00  2.38    73.28  0.00     8.76
39  206.0          1.51732   14.95  0.00  1.80    72.99  0.00     8.61
40  187.0          1.51838   14.32  3.26  2.22    71.25  1.46     5.79
41  209.0          1.51640   14.37  0.00  2.74    72.85  0.00     9.45
42  191.0          1.51613   13.88  1.78  1.79    73.10  0.00     8.67
43  196.0          1.51545   14.14  0.00  2.68    73.39  0.08     9.07

    Barium  Iron  GlassType  Predicted Class Prediction Correct?
0     0.00  0.11        1.0              1.0                 Yes
1     0.00  0.00        1.0              1.0                 Yes
2     0.00  0.00        1.0              1.0                 Yes
3     0.00  0.00        1.0              1.0                 Yes
4     0.00  0.00        1.0              1.0                 Yes
5     0.00  0.00        1.0              1.0                 Yes
6     0.00  0.17        1.0              1.0                 Yes
7     0.00  0.00        1.0              1.0                 Yes
8     0.00  0.00        1.0              1.0                 Yes
9     0.00  0.00        1.0              1.0                 Yes
10    0.00  0.00        1.0              1.0                 Yes
11    0.69  0.00        1.0              1.0                 Yes
12    0.00  0.00        1.0              1.0                 Yes
13    0.00  0.00        1.0              1.0                 Yes
14    0.00  0.00        2.0              1.0                  No
15    0.00  0.00        2.0              1.0                  No
16    0.00  0.17        2.0              1.0                  No
17    0.00  0.00        2.0              1.0                  No
18    0.00  0.18        2.0              1.0                  No
19    0.00  0.35        2.0              1.0                  No
20    0.00  0.00        2.0              1.0                  No
21    0.00  0.12        2.0              1.0                  No
22    0.00  0.10        2.0              1.0                  No
23    0.00  0.24        2.0              1.0                  No
24    0.00  0.00        2.0              1.0                  No
25    0.06  0.25        2.0              1.0                  No
26    0.00  0.00        2.0              1.0                  No
27    0.00  0.00        2.0              1.0                  No
28    0.00  0.00        2.0              1.0                  No
29    0.00  0.00        3.0              1.0                  No
30    0.00  0.00        3.0              1.0                  No
31    0.00  0.09        3.0              1.0                  No
32    0.00  0.10        3.0              1.0                  No
33    0.00  0.00        5.0              1.0                  No
34    0.00  0.00        5.0              1.0                  No
35    0.00  0.00        5.0              1.0                  No
36    0.00  0.00        6.0              1.0                  No
37    0.00  0.00        6.0              1.0                  No
38    0.64  0.09        7.0              1.0                  No
39    1.55  0.00        7.0              1.0                  No
40    1.63  0.00        7.0              1.0                  No
41    0.54  0.00        7.0              1.0                  No
42    0.76  0.00        7.0              1.0                  No
43    0.61  0.05        7.0              1.0                  No

Learned Model (Likelihood Table):
                                        0
RefractiveIndex1.51783999999999991.0  1.0
RefractiveIndex1.519051.0             1.0
RefractiveIndex1.517681.0             1.0
RefractiveIndex1.517931.0             1.0
RefractiveIndex1.5191.0               1.0
...                                   ...
Iron0.097.0                           0.1
Iron0.317.0                           0.0
Iron0.347.0                           0.0
Iron0.37.0                            0.0
Iron0.077.0                           0.1

[4806 rows x 1 columns]

Number of Test Instances:
44


Running Experiment 3 ...

Accuracy:
32.55813953488372%

Classifications:
       ID  RefractiveIndex  Sodium   Mag  Alum  Silicon     K  Calcium  \
0    56.0          1.51769   12.45  2.71  1.29    73.70  0.56     9.06
1    34.0          1.51753   12.57  3.47  1.38    73.39  0.60     8.55
2    50.0          1.51898   13.58  3.35  1.23    72.08  0.59     8.91
3    59.0          1.51754   13.48  3.74  1.17    72.99  0.59     8.03
4     6.0          1.51596   12.79  3.61  1.62    72.97  0.64     8.07
5     9.0          1.51918   14.04  3.58  1.37    72.08  0.56     8.30
6    51.0          1.52320   13.72  3.72  0.51    71.75  0.09    10.06
7    11.0          1.51571   12.72  3.46  1.56    73.20  0.67     8.09
8    44.0          1.52210   13.73  3.84  0.72    71.76  0.17     9.74
9    10.0          1.51755   13.00  3.60  1.36    72.99  0.57     8.40
10   66.0          1.52099   13.69  3.59  1.12    71.96  0.09     9.40
11   60.0          1.51754   13.39  3.66  1.19    72.79  0.57     8.27
12   21.0          1.51750   12.82  3.55  1.49    72.75  0.54     8.52
13   48.0          1.52667   13.99  3.70  0.71    71.57  0.02     9.82
14   83.0          1.51646   13.41  3.55  1.25    72.81  0.68     8.10
15  111.0          1.52664   11.23  0.00  0.77    73.21  0.00    14.68
16  101.0          1.51655   12.75  2.85  1.44    73.27  0.57     8.79
17   72.0          1.51848   13.64  3.87  1.27    71.96  0.54     8.32
18  113.0          1.52777   12.64  0.00  0.67    72.02  0.06    14.40
19  142.0          1.51851   13.20  3.63  1.07    72.83  0.57     8.41
20  119.0          1.51673   13.30  3.64  1.53    72.53  0.65     8.03
21   80.0          1.51590   12.82  3.52  1.90    72.86  0.69     7.97
22  141.0          1.51690   13.33  3.54  1.61    72.54  0.68     8.11
23   93.0          1.51588   13.12  3.41  1.58    73.26  0.07     8.39
24  139.0          1.51674   12.79  3.52  1.54    73.36  0.66     7.90
25   97.0          1.51841   13.02  3.62  1.06    72.34  0.64     9.13
26  137.0          1.51806   13.00  3.80  1.08    73.07  0.56     8.38
27  135.0          1.51811   13.33  3.85  1.25    72.78  0.52     8.12
28  100.0          1.51811   12.96  2.96  1.43    72.92  0.60     8.79
29  162.0          1.51934   13.64  3.54  0.75    72.65  0.16     8.89
30  157.0          1.51655   13.41  3.39  1.28    72.64  0.52     8.65
31  163.0          1.52211   14.19  3.78  0.91    71.36  0.23     9.14
32  174.0          1.52043   13.38  0.00  1.40    72.25  0.33    12.50
33  176.0          1.52119   12.97  0.33  1.51    73.39  0.13    11.27
34  172.0          1.51316   13.02  0.00  3.04    70.48  6.21     6.96
35  182.0          1.51888   14.99  0.78  1.74    72.50  0.00     9.95
36  178.0          1.51937   13.79  2.41  1.19    72.76  0.00     9.77
37  190.0          1.52365   15.79  1.83  1.31    70.43  0.31     8.61
38  200.0          1.51609   15.01  0.00  2.51    73.05  0.05     8.83
39  208.0          1.51831   14.39  0.00  1.82    72.86  1.41     6.47
40  194.0          1.51719   14.75  0.00  2.00    73.02  0.00     8.53
41  186.0          1.51131   13.69  3.20  1.81    72.81  1.76     5.43
42  203.0          1.51514   14.85  0.00  2.42    73.72  0.00     8.39

    Barium  Iron  GlassType  Predicted Class Prediction Correct?
0     0.00  0.24        1.0              1.0                 Yes
1     0.00  0.06        1.0              1.0                 Yes
2     0.00  0.00        1.0              1.0                 Yes
3     0.00  0.00        1.0              1.0                 Yes
4     0.00  0.26        1.0              1.0                 Yes
5     0.00  0.00        1.0              1.0                 Yes
6     0.00  0.16        1.0              1.0                 Yes
7     0.00  0.24        1.0              1.0                 Yes
8     0.00  0.00        1.0              1.0                 Yes
9     0.00  0.11        1.0              1.0                 Yes
10    0.00  0.00        1.0              1.0                 Yes
11    0.00  0.11        1.0              1.0                 Yes
12    0.00  0.19        1.0              1.0                 Yes
13    0.00  0.10        1.0              1.0                 Yes
14    0.00  0.00        2.0              1.0                  No
15    0.00  0.00        2.0              1.0                  No
16    0.11  0.22        2.0              1.0                  No
17    0.00  0.32        2.0              1.0                  No
18    0.00  0.00        2.0              1.0                  No
19    0.09  0.17        2.0              1.0                  No
20    0.00  0.29        2.0              1.0                  No
21    0.00  0.00        2.0              1.0                  No
22    0.00  0.00        2.0              1.0                  No
23    0.00  0.19        2.0              1.0                  No
24    0.00  0.00        2.0              1.0                  No
25    0.00  0.15        2.0              1.0                  No
26    0.00  0.12        2.0              1.0                  No
27    0.00  0.00        2.0              1.0                  No
28    0.14  0.00        2.0              1.0                  No
29    0.15  0.24        3.0              1.0                  No
30    0.00  0.00        3.0              1.0                  No
31    0.00  0.37        3.0              1.0                  No
32    0.00  0.00        5.0              1.0                  No
33    0.00  0.28        5.0              1.0                  No
34    0.00  0.00        5.0              1.0                  No
35    0.00  0.00        6.0              1.0                  No
36    0.00  0.00        6.0              1.0                  No
37    1.68  0.00        7.0              1.0                  No
38    0.53  0.00        7.0              1.0                  No
39    2.88  0.00        7.0              1.0                  No
40    1.59  0.08        7.0              1.0                  No
41    1.19  0.00        7.0              1.0                  No
42    0.56  0.00        7.0              1.0                  No

Learned Model (Likelihood Table):
                                        0
RefractiveIndex1.51783999999999991.0  1.0
RefractiveIndex1.519051.0             1.0
RefractiveIndex1.517681.0             1.0
RefractiveIndex1.517931.0             1.0
RefractiveIndex1.5191.0               1.0
...                                   ...
Iron0.287.0                           0.0
Iron0.087.0                           0.0
Iron0.347.0                           0.0
Iron0.37.0                            0.0
Iron0.077.0                           0.1

[4722 rows x 1 columns]

Number of Test Instances:
43


Running Experiment 4 ...

Accuracy:
33.33333333333333%

Classifications:
       ID  RefractiveIndex  Sodium   Mag  Alum  Silicon     K  Calcium  \
0    36.0          1.51567   13.29  3.45  1.21    72.74  0.56     8.57
1    22.0          1.51966   14.77  3.75  0.29    72.02  0.03     9.00
2     3.0          1.51618   13.53  3.55  1.54    72.99  0.39     7.78
3    19.0          1.51911   13.90  3.73  1.18    72.12  0.06     8.89
4     4.0          1.51766   13.21  3.69  1.29    72.61  0.57     8.22
5    33.0          1.51775   12.85  3.48  1.23    72.97  0.61     8.56
6    63.0          1.52172   13.51  3.86  0.88    71.79  0.23     9.54
7     5.0          1.51742   13.27  3.62  1.24    73.08  0.55     8.07
8    55.0          1.51778   13.21  2.81  1.29    72.98  0.51     9.02
9    57.0          1.51215   12.99  3.47  1.12    72.98  0.62     8.35
10   69.0          1.52152   13.12  3.58  0.90    72.20  0.23     9.82
11   18.0          1.52196   14.36  3.85  0.89    71.36  0.15     9.15
12   42.0          1.51755   12.71  3.42  1.20    73.20  0.59     8.64
13    8.0          1.51756   13.15  3.61  1.05    73.24  0.57     8.24
14  125.0          1.52177   13.20  3.68  1.15    72.75  0.54     8.52
15  121.0          1.51844   13.25  3.76  1.32    72.40  0.58     8.42
16  117.0          1.51829   13.24  3.90  1.41    72.33  0.55     8.31
17  138.0          1.51711   12.89  3.62  1.57    72.96  0.61     8.11
18  107.0          1.53125   10.73  0.00  2.10    69.81  0.58    13.30
19   75.0          1.51596   13.02  3.56  1.54    73.11  0.72     7.90
20  104.0          1.52725   13.80  3.15  0.66    70.57  0.08    11.64
21   81.0          1.51592   12.86  3.52  2.12    72.66  0.69     7.97
22   95.0          1.51629   12.71  3.33  1.49    73.28  0.67     8.24
23   90.0          1.51640   12.55  3.48  1.87    73.23  0.63     8.08
24   88.0          1.51645   13.40  3.49  1.52    72.65  0.67     8.08
25  109.0          1.52222   14.43  0.00  1.00    72.67  0.10    11.52
26   87.0          1.51569   13.24  3.49  1.47    73.25  0.38     8.03
27  106.0          1.52475   11.45  0.00  1.88    72.19  0.81    13.24
28   94.0          1.51590   13.24  3.34  1.47    73.10  0.39     8.22
29  147.0          1.51769   13.65  3.66  1.11    72.77  0.11     8.60
30  148.0          1.51610   13.33  3.53  1.34    72.67  0.56     8.33
31  158.0          1.52121   14.03  3.76  0.58    71.79  0.11     9.65
32  170.0          1.51994   13.27  0.00  1.76    73.03  0.47    11.32
33  166.0          1.52171   11.56  1.88  1.56    72.86  0.47    11.41
34  177.0          1.51905   14.00  2.39  1.56    72.37  0.00     9.57
35  181.0          1.51299   14.40  1.74  1.54    74.55  0.00     7.59
36  207.0          1.51645   14.94  0.00  1.87    73.11  0.00     8.67
37  201.0          1.51508   15.15  0.00  2.25    73.50  0.00     8.34
38  212.0          1.52065   14.36  0.00  2.02    73.42  0.00     8.44
39  211.0          1.51685   14.92  0.00  1.99    73.06  0.00     8.40
40  213.0          1.51651   14.38  0.00  1.94    73.61  0.00     8.48
41  198.0          1.51727   14.70  0.00  2.34    73.28  0.00     8.95

    Barium  Iron  GlassType  Predicted Class Prediction Correct?
0     0.00  0.00        1.0              1.0                 Yes
1     0.00  0.00        1.0              1.0                 Yes
2     0.00  0.00        1.0              1.0                 Yes
3     0.00  0.00        1.0              1.0                 Yes
4     0.00  0.00        1.0              1.0                 Yes
5     0.09  0.22        1.0              1.0                 Yes
6     0.00  0.11        1.0              1.0                 Yes
7     0.00  0.00        1.0              1.0                 Yes
8     0.00  0.09        1.0              1.0                 Yes
9     0.00  0.31        1.0              1.0                 Yes
10    0.00  0.16        1.0              1.0                 Yes
11    0.00  0.00        1.0              1.0                 Yes
12    0.00  0.00        1.0              1.0                 Yes
13    0.00  0.00        1.0              1.0                 Yes
14    0.00  0.00        2.0              1.0                  No
15    0.00  0.00        2.0              1.0                  No
16    0.00  0.10        2.0              1.0                  No
17    0.00  0.00        2.0              1.0                  No
18    3.15  0.28        2.0              1.0                  No
19    0.00  0.00        2.0              1.0                  No
20    0.00  0.00        2.0              1.0                  No
21    0.00  0.00        2.0              1.0                  No
22    0.00  0.00        2.0              1.0                  No
23    0.00  0.09        2.0              1.0                  No
24    0.00  0.10        2.0              1.0                  No
25    0.00  0.08        2.0              1.0                  No
26    0.00  0.00        2.0              1.0                  No
27    0.00  0.34        2.0              1.0                  No
28    0.00  0.00        2.0              1.0                  No
29    0.00  0.00        3.0              1.0                  No
30    0.00  0.00        3.0              1.0                  No
31    0.00  0.00        3.0              1.0                  No
32    0.00  0.00        5.0              1.0                  No
33    0.00  0.00        5.0              1.0                  No
34    0.00  0.00        6.0              1.0                  No
35    0.00  0.00        6.0              1.0                  No
36    1.38  0.00        7.0              1.0                  No
37    0.63  0.00        7.0              1.0                  No
38    1.64  0.00        7.0              1.0                  No
39    1.59  0.00        7.0              1.0                  No
40    1.57  0.00        7.0              1.0                  No
41    0.66  0.00        7.0              1.0                  No

Learned Model (Likelihood Table):
                                             0
RefractiveIndex1.51783999999999991.0  1.000000
RefractiveIndex1.519051.0             1.000000
RefractiveIndex1.517681.0             1.000000
RefractiveIndex1.517931.0             1.000000
RefractiveIndex1.5191.0               1.000000
...                                        ...
Iron0.377.0                           0.000000
Iron0.287.0                           0.000000
Iron0.087.0                           0.090909
Iron0.37.0                            0.000000
Iron0.077.0                           0.090909

[4830 rows x 1 columns]

Number of Test Instances:
42


Running Experiment 5 ...

Accuracy:
33.33333333333333%

Classifications:
       ID  RefractiveIndex  Sodium   Mag  Alum  Silicon     K  Calcium  \
0    47.0          1.51869   13.19  3.37  1.18    72.72  0.57     8.83
1    37.0          1.51909   13.89  3.53  1.32    71.81  0.51     8.78
2    15.0          1.51763   12.61  3.59  1.31    73.29  0.58     8.50
3    27.0          1.51793   13.21  3.48  1.41    72.64  0.59     8.43
4    53.0          1.51808   13.43  2.87  1.19    72.84  0.55     9.03
5    38.0          1.51797   12.74  3.48  1.35    72.96  0.64     8.68
6    68.0          1.52152   13.05  3.65  0.87    72.32  0.19     9.85
7    64.0          1.52227   14.17  3.81  0.78    71.35  0.00     9.69
8    43.0          1.51779   13.21  3.39  1.33    72.76  0.59     8.59
9    45.0          1.51786   12.73  3.43  1.19    72.95  0.62     8.76
10   20.0          1.51735   13.02  3.54  1.69    72.73  0.54     8.44
11   23.0          1.51736   12.78  3.62  1.29    72.79  0.59     8.70
12   65.0          1.52172   13.48  3.74  0.90    72.01  0.18     9.61
13   74.0          1.51631   13.34  3.57  1.57    72.87  0.61     7.89
14  116.0          1.51846   13.41  3.89  1.33    72.38  0.51     8.28
15   84.0          1.51594   13.09  3.52  1.55    72.87  0.68     8.05
16   86.0          1.51625   13.36  3.58  1.49    72.72  0.45     8.21
17   98.0          1.51743   12.20  3.25  1.16    73.55  0.62     8.90
18  120.0          1.51652   13.56  3.57  1.47    72.45  0.64     7.96
19  105.0          1.52410   13.83  2.90  1.17    71.15  0.08    10.79
20   92.0          1.51605   12.90  3.44  1.45    73.06  0.44     8.27
21  131.0          1.52177   13.75  1.01  1.36    72.19  0.33    11.14
22  136.0          1.51789   13.19  3.90  1.30    72.33  0.55     8.44
23   89.0          1.51618   13.01  3.50  1.48    72.89  0.60     8.12
24  144.0          1.51709   13.00  3.47  1.79    72.72  0.66     8.18
25  108.0          1.53393   12.30  0.00  1.00    70.16  0.12    16.19
26   78.0          1.51627   13.00  3.58  1.54    72.83  0.61     8.04
27  133.0          1.51813   13.43  3.98  1.18    72.49  0.58     8.15
28  153.0          1.51779   13.64  3.65  0.65    73.00  0.06     8.93
29  156.0          1.51646   13.04  3.40  1.26    73.01  0.52     8.58
30  161.0          1.51832   13.33  3.34  1.54    72.14  0.56     8.99
31  173.0          1.51321   13.00  0.00  3.02    70.70  6.21     6.93
32  165.0          1.51915   12.73  1.85  1.86    72.69  0.60    10.09
33  184.0          1.51969   14.56  0.00  0.56    73.48  0.00    11.22
34  210.0          1.51623   14.14  0.00  2.88    72.61  0.08     9.18
35  195.0          1.51683   14.56  0.00  1.98    73.29  0.00     8.52
36  199.0          1.51531   14.38  0.00  2.66    73.10  0.04     9.08
37  193.0          1.51623   14.20  0.00  2.79    73.46  0.04     9.04
38  189.0          1.52247   14.86  2.20  2.06    70.26  0.76     9.76

    Barium  Iron  GlassType  Predicted Class Prediction Correct?
0     0.00  0.16        1.0              1.0                 Yes
1     0.11  0.00        1.0              1.0                 Yes
2     0.00  0.00        1.0              1.0                 Yes
3     0.00  0.00        1.0              1.0                 Yes
4     0.00  0.00        1.0              1.0                 Yes
5     0.00  0.00        1.0              1.0                 Yes
6     0.00  0.17        1.0              1.0                 Yes
7     0.00  0.00        1.0              1.0                 Yes
8     0.00  0.00        1.0              1.0                 Yes
9     0.00  0.30        1.0              1.0                 Yes
10    0.00  0.07        1.0              1.0                 Yes
11    0.00  0.00        1.0              1.0                 Yes
12    0.00  0.07        1.0              1.0                 Yes
13    0.00  0.00        2.0              1.0                  No
14    0.00  0.00        2.0              1.0                  No
15    0.00  0.09        2.0              1.0                  No
16    0.00  0.00        2.0              1.0                  No
17    0.00  0.24        2.0              1.0                  No
18    0.00  0.00        2.0              1.0                  No
19    0.00  0.00        2.0              1.0                  No
20    0.00  0.00        2.0              1.0                  No
21    0.00  0.00        2.0              1.0                  No
22    0.00  0.28        2.0              1.0                  No
23    0.00  0.00        2.0              1.0                  No
24    0.00  0.00        2.0              1.0                  No
25    0.00  0.24        2.0              1.0                  No
26    0.00  0.00        2.0              1.0                  No
27    0.00  0.00        2.0              1.0                  No
28    0.00  0.00        3.0              1.0                  No
29    0.00  0.00        3.0              1.0                  No
30    0.00  0.00        3.0              1.0                  No
31    0.00  0.00        5.0              1.0                  No
32    0.00  0.00        5.0              1.0                  No
33    0.00  0.00        6.0              1.0                  No
34    1.06  0.00        7.0              1.0                  No
35    1.57  0.07        7.0              1.0                  No
36    0.64  0.00        7.0              1.0                  No
37    0.40  0.09        7.0              1.0                  No
38    0.00  0.00        7.0              1.0                  No

Learned Model (Likelihood Table):
                                             0
RefractiveIndex1.51783999999999991.0  1.000000
RefractiveIndex1.519051.0             1.000000
RefractiveIndex1.517681.0             1.000000
RefractiveIndex1.517931.0             1.000000
RefractiveIndex1.5191.0               1.000000
...                                        ...
Iron0.377.0                           0.000000
Iron0.287.0                           0.000000
Iron0.087.0                           0.090909
Iron0.317.0                           0.000000
Iron0.347.0                           0.000000

[4926 rows x 1 columns]

Number of Test Instances:
39

Experiments Completed.


----------------------------------------------------------
Naive Bayes Summary Statistics
----------------------------------------------------------
Data Set : Glass.txt


Accuracy Statistics for All 5 Experiments:
[0.31111111 0.31818182 0.3255814  0.33333333 0.33333333]


Classification Accuracy : 32.43081982616866%

#### Iris

In [38]:
Data = Iris
DataPath = "Iris.txt"
TraceRunFile = "Bayes/Iris/TraceFile.txt"
StatsFile = "Bayes/Iris/TestStats.txt"
BayesMain.BayesMain(Data, DataPath, TraceRunFile, StatsFile)

Naive Bayes Program!


Running Experiment 1 ...

Accuracy:
86.66666666666667%

Classifications:
    Sepal_L  Sepal_W  Petal_L  Petal_W  Class  Predicted Class  \
0       5.0      3.2      1.2      0.2    0.0              0.0
1       5.8      4.0      1.2      0.2    0.0              0.0
2       4.5      2.3      1.3      0.3    0.0              0.0
3       5.3      3.7      1.5      0.2    0.0              0.0
4       4.9      3.1      1.5      0.1    0.0              0.0
5       4.6      3.1      1.5      0.2    0.0              0.0
6       4.8      3.4      1.6      0.2    0.0              0.0
7       5.5      3.5      1.3      0.2    0.0              0.0
8       4.4      2.9      1.4      0.2    0.0              0.0
9       4.6      3.2      1.4      0.2    0.0              0.0
10      7.4      2.8      6.1      1.9    1.0              1.0
11      7.7      2.8      6.7      2.0    1.0              1.0
12      6.2      2.8      4.8      1.8    1.0              1.0
13      7.7      3.0      6.1      2.3    1.0              1.0
14      6.7      3.3      5.7      2.5    1.0              1.0
15      5.7      2.5      5.0      2.0    1.0              1.0
16      7.1      3.0      5.9      2.1    1.0              1.0
17      6.3      3.4      5.6      2.4    1.0              1.0
18      5.8      2.7      5.1      1.9    1.0              1.0
19      6.0      2.2      5.0      1.5    1.0              0.0
20      6.4      2.9      4.3      1.3    2.0              2.0
21      5.0      2.3      3.3      1.0    2.0              2.0
22      6.7      3.0      5.0      1.7    2.0              1.0
23      6.3      2.3      4.4      1.3    2.0              2.0
24      5.8      2.6      4.0      1.2    2.0              2.0
25      5.5      2.6      4.4      1.2    2.0              2.0
26      6.7      3.1      4.7      1.5    2.0              2.0
27      6.3      3.3      4.7      1.6    2.0              0.0
28      6.9      3.1      4.9      1.5    2.0              1.0
29      6.2      2.2      4.5      1.5    2.0              2.0

   Prediction Correct?
0                  Yes
1                  Yes
2                  Yes
3                  Yes
4                  Yes
5                  Yes
6                  Yes
7                  Yes
8                  Yes
9                  Yes
10                 Yes
11                 Yes
12                 Yes
13                 Yes
14                 Yes
15                 Yes
16                 Yes
17                 Yes
18                 Yes
19                  No
20                 Yes
21                 Yes
22                  No
23                 Yes
24                 Yes
25                 Yes
26                 Yes
27                  No
28                  No
29                 Yes

Learned Model (Likelihood Table):
                      0
Sepal_W3.10.0  0.076923
Sepal_W3.00.0  0.153846
Sepal_W3.40.0  0.205128
Sepal_W3.30.0  0.051282
Sepal_W4.40.0  0.025641
...                 ...
Petal_W1.72.0  0.000000
Petal_W0.62.0  0.000000
Petal_W2.52.0  0.000000
Petal_W2.42.0  0.000000
Petal_W0.52.0  0.000000

[258 rows x 1 columns]

Number of Test Instances:
30


Running Experiment 2 ...

Accuracy:
80.0%

Classifications:
    Sepal_L  Sepal_W  Petal_L  Petal_W  Class  Predicted Class  \
0       4.8      3.1      1.6      0.2    0.0              0.0
1       4.3      3.0      1.1      0.1    0.0              0.0
2       5.4      3.4      1.7      0.2    0.0              0.0
3       5.0      3.3      1.4      0.2    0.0              0.0
4       5.7      4.4      1.5      0.4    0.0              0.0
5       5.1      3.8      1.6      0.2    0.0              0.0
6       4.8      3.4      1.9      0.2    0.0              0.0
7       5.0      3.4      1.5      0.2    0.0              0.0
8       5.4      3.4      1.5      0.4    0.0              0.0
9       5.7      3.8      1.7      0.3    0.0              0.0
10      7.2      3.0      5.8      1.6    1.0              0.0
11      6.8      3.0      5.5      2.1    1.0              1.0
12      6.2      3.4      5.4      2.3    1.0              1.0
13      7.6      3.0      6.6      2.1    1.0              0.0
14      6.5      3.2      5.1      2.0    1.0              1.0
15      6.4      2.8      5.6      2.1    1.0              1.0
16      6.1      3.0      4.9      1.8    1.0              1.0
17      7.9      3.8      6.4      2.0    1.0              0.0
18      6.4      3.1      5.5      1.8    1.0              1.0
19      7.3      2.9      6.3      1.8    1.0              0.0
20      6.3      2.5      4.9      1.5    2.0              1.0
21      5.9      3.0      4.2      1.5    2.0              2.0
22      5.6      3.0      4.5      1.5    2.0              2.0
23      4.9      2.4      3.3      1.0    2.0              2.0
24      5.5      2.5      4.0      1.3    2.0              2.0
25      7.0      3.2      4.7      1.4    2.0              2.0
26      5.6      2.5      3.9      1.1    2.0              2.0
27      6.5      2.8      4.6      1.5    2.0              2.0
28      5.7      3.0      4.2      1.2    2.0              2.0
29      6.0      2.7      5.1      1.6    2.0              0.0

   Prediction Correct?
0                  Yes
1                  Yes
2                  Yes
3                  Yes
4                  Yes
5                  Yes
6                  Yes
7                  Yes
8                  Yes
9                  Yes
10                  No
11                 Yes
12                 Yes
13                  No
14                 Yes
15                 Yes
16                 Yes
17                  No
18                 Yes
19                  No
20                  No
21                 Yes
22                 Yes
23                 Yes
24                 Yes
25                 Yes
26                 Yes
27                 Yes
28                 Yes
29                  No

Learned Model (Likelihood Table):
                      0
Sepal_W3.20.0  0.128205
Sepal_W4.00.0  0.025641
Sepal_W2.30.0  0.025641
Sepal_W3.70.0  0.076923
Sepal_W3.10.0  0.102564
...                 ...
Petal_W2.22.0  0.000000
Petal_W1.42.0  0.150000
Petal_W0.62.0  0.000000
Petal_W0.52.0  0.000000
Petal_W1.12.0  0.050000

[249 rows x 1 columns]

Number of Test Instances:
30


Running Experiment 3 ...

Accuracy:
80.0%

Classifications:
    Sepal_L  Sepal_W  Petal_L  Petal_W  Class  Predicted Class  \
0       4.9      3.1      1.5      0.1    0.0              0.0
1       5.4      3.9      1.3      0.4    0.0              0.0
2       4.6      3.6      1.0      0.2    0.0              0.0
3       5.0      3.4      1.6      0.4    0.0              0.0
4       4.7      3.2      1.3      0.2    0.0              0.0
5       5.0      3.5      1.3      0.3    0.0              0.0
6       4.9      3.1      1.5      0.1    0.0              0.0
7       4.6      3.4      1.4      0.3    0.0              0.0
8       5.2      3.5      1.5      0.2    0.0              0.0
9       5.2      3.4      1.4      0.2    0.0              0.0
10      6.7      3.0      5.2      2.3    1.0              0.0
11      7.7      3.8      6.7      2.2    1.0              1.0
12      7.7      2.6      6.9      2.3    1.0              0.0
13      6.4      2.8      5.6      2.2    1.0              1.0
14      6.9      3.1      5.1      2.3    1.0              1.0
15      5.8      2.7      5.1      1.9    1.0              1.0
16      6.3      2.7      4.9      1.8    1.0              1.0
17      4.9      2.5      4.5      1.7    1.0              2.0
18      6.5      3.0      5.2      2.0    1.0              0.0
19      6.3      2.5      5.0      1.9    1.0              1.0
20      6.0      3.4      4.5      1.6    2.0              0.0
21      6.1      2.9      4.7      1.4    2.0              2.0
22      6.8      2.8      4.8      1.4    2.0              2.0
23      6.6      3.0      4.4      1.4    2.0              2.0
24      5.5      2.4      3.7      1.0    2.0              0.0
25      5.7      2.8      4.5      1.3    2.0              2.0
26      6.0      2.2      4.0      1.0    2.0              2.0
27      5.8      2.7      3.9      1.2    2.0              2.0
28      6.6      2.9      4.6      1.3    2.0              2.0
29      6.2      2.9      4.3      1.3    2.0              2.0

   Prediction Correct?
0                  Yes
1                  Yes
2                  Yes
3                  Yes
4                  Yes
5                  Yes
6                  Yes
7                  Yes
8                  Yes
9                  Yes
10                  No
11                 Yes
12                  No
13                 Yes
14                 Yes
15                 Yes
16                 Yes
17                  No
18                  No
19                 Yes
20                  No
21                 Yes
22                 Yes
23                 Yes
24                  No
25                 Yes
26                 Yes
27                 Yes
28                 Yes
29                 Yes

Learned Model (Likelihood Table):
                      0
Sepal_W3.20.0  0.102564
Sepal_W4.00.0  0.025641
Sepal_W2.30.0  0.025641
Sepal_W3.70.0  0.076923
Sepal_W3.10.0  0.076923
...                 ...
Petal_W1.42.0  0.100000
Petal_W1.12.0  0.075000
Petal_W0.62.0  0.000000
Petal_W2.22.0  0.000000
Petal_W0.52.0  0.000000

[252 rows x 1 columns]

Number of Test Instances:
30


Running Experiment 4 ...

Accuracy:
90.0%

Classifications:
    Sepal_L  Sepal_W  Petal_L  Petal_W  Class  Predicted Class  \
0       5.4      3.7      1.5      0.2    0.0              0.0
1       5.0      3.5      1.6      0.6    0.0              0.0
2       4.4      3.2      1.3      0.2    0.0              0.0
3       5.1      3.8      1.5      0.3    0.0              0.0
4       5.0      3.0      1.6      0.2    0.0              0.0
5       5.2      4.1      1.5      0.1    0.0              0.0
6       4.8      3.0      1.4      0.3    0.0              0.0
7       4.7      3.2      1.6      0.2    0.0              0.0
8       5.0      3.6      1.4      0.2    0.0              0.0
9       4.4      3.0      1.3      0.2    0.0              0.0
10      5.6      2.8      4.9      2.0    1.0              1.0
11      7.2      3.6      6.1      2.5    1.0              0.0
12      7.2      3.2      6.0      1.8    1.0              0.0
13      6.7      3.3      5.7      2.1    1.0              1.0
14      6.5      3.0      5.8      2.2    1.0              1.0
15      6.7      3.1      5.6      2.4    1.0              1.0
16      5.8      2.8      5.1      2.4    1.0              1.0
17      6.0      3.0      4.8      1.8    1.0              1.0
18      6.3      3.3      6.0      2.5    1.0              0.0
19      6.8      3.2      5.9      2.3    1.0              1.0
20      6.7      3.1      4.4      1.4    2.0              2.0
21      5.6      2.7      4.2      1.3    2.0              2.0
22      6.4      3.2      4.5      1.5    2.0              2.0
23      5.5      2.3      4.0      1.3    2.0              2.0
24      6.0      2.9      4.5      1.5    2.0              2.0
25      5.7      2.6      3.5      1.0    2.0              2.0
26      5.7      2.8      4.1      1.3    2.0              2.0
27      5.4      3.0      4.5      1.5    2.0              2.0
28      5.8      2.7      4.1      1.0    2.0              2.0
29      6.1      3.0      4.6      1.4    2.0              2.0

   Prediction Correct?
0                  Yes
1                  Yes
2                  Yes
3                  Yes
4                  Yes
5                  Yes
6                  Yes
7                  Yes
8                  Yes
9                  Yes
10                 Yes
11                  No
12                  No
13                 Yes
14                 Yes
15                 Yes
16                 Yes
17                 Yes
18                  No
19                 Yes
20                 Yes
21                 Yes
22                 Yes
23                 Yes
24                 Yes
25                 Yes
26                 Yes
27                 Yes
28                 Yes
29                 Yes

Learned Model (Likelihood Table):
                      0
Sepal_W3.20.0  0.076923
Sepal_W4.00.0  0.025641
Sepal_W2.30.0  0.025641
Sepal_W3.70.0  0.051282
Sepal_W3.10.0  0.128205
...                 ...
Petal_W0.42.0  0.000000
Petal_W1.42.0  0.125000
Petal_W1.12.0  0.075000
Petal_W2.22.0  0.000000
Petal_W0.52.0  0.000000

[255 rows x 1 columns]

Number of Test Instances:
30


Running Experiment 5 ...

Accuracy:
68.96551724137932%

Classifications:
    Sepal_L  Sepal_W  Petal_L  Petal_W  Class  Predicted Class  \
0       5.4      3.9      1.7      0.4    0.0              0.0
1       4.8      3.0      1.4      0.1    0.0              0.0
2       5.1      3.7      1.5      0.4    0.0              0.0
3       5.1      3.4      1.5      0.2    0.0              0.0
4       5.1      3.8      1.9      0.4    0.0              0.0
5       5.1      3.5      1.4      0.3    0.0              0.0
6       5.1      3.3      1.7      0.5    0.0              0.0
7       5.5      4.2      1.4      0.2    0.0              0.0
8       4.9      3.0      1.4      0.2    0.0              0.0
9       6.9      3.1      5.4      2.1    1.0              1.0
10      6.4      3.2      5.3      2.3    1.0              0.0
11      6.9      3.2      5.7      2.3    1.0              1.0
12      6.7      2.5      5.8      1.8    1.0              1.0
13      6.4      2.7      5.3      1.9    1.0              0.0
14      5.9      3.0      5.1      1.8    1.0              1.0
15      6.3      2.8      5.1      1.5    1.0              2.0
16      6.3      2.9      5.6      1.8    1.0              1.0
17      6.1      2.6      5.6      1.4    1.0              0.0
18      6.5      3.0      5.5      1.8    1.0              1.0
19      5.2      2.7      3.9      1.4    2.0              2.0
20      5.1      2.5      3.0      1.1    2.0              0.0
21      5.5      2.4      3.8      1.1    2.0              0.0
22      5.6      2.9      3.6      1.3    2.0              0.0
23      5.7      2.9      4.2      1.3    2.0              2.0
24      5.0      2.0      3.5      1.0    2.0              0.0
25      5.6      3.0      4.1      1.3    2.0              2.0
26      6.1      2.8      4.7      1.2    2.0              2.0
27      5.9      3.2      4.8      1.8    2.0              1.0
28      6.1      2.8      4.0      1.3    2.0              2.0

   Prediction Correct?
0                  Yes
1                  Yes
2                  Yes
3                  Yes
4                  Yes
5                  Yes
6                  Yes
7                  Yes
8                  Yes
9                  Yes
10                  No
11                 Yes
12                 Yes
13                  No
14                 Yes
15                  No
16                 Yes
17                  No
18                 Yes
19                 Yes
20                  No
21                  No
22                  No
23                 Yes
24                  No
25                 Yes
26                 Yes
27                  No
28                 Yes

Learned Model (Likelihood Table):
                   0
Sepal_W3.20.0  0.125
Sepal_W4.00.0  0.025
Sepal_W2.30.0  0.025
Sepal_W3.70.0  0.050
Sepal_W3.10.0  0.125
...              ...
Petal_W0.42.0  0.000
Petal_W1.42.0  0.150
Petal_W1.12.0  0.025
Petal_W2.22.0  0.000
Petal_W0.62.0  0.000

[243 rows x 1 columns]

Number of Test Instances:
29

Experiments Completed.


----------------------------------------------------------
Naive Bayes Summary Statistics
----------------------------------------------------------
Data Set : Iris.txt


Accuracy Statistics for All 5 Experiments:
[0.86666667 0.8        0.8        0.9        0.68965517]


Classification Accuracy : 81.1264367816092%

#### Soybean

In [39]:
Data = SoyBean
DataPath = "SoyBean.txt"
TraceRunFile = "Bayes/SoyBean/TraceFile.txt"
StatsFile = "Bayes/SoyBean/TestStats.txt"
BayesMain.BayesMain(Data, DataPath, TraceRunFile, StatsFile)

Naive Bayes Program!


Running Experiment 1 ...

Accuracy:
80.0%

Classifications:
  date plantstand precip temp hail crophist areadamaged severity seedtmt  \
0    4          0      2    1    0        3           0        2       0
1    6          0      2    1    0        1           1        1       0
2    6          0      0    2    1        0           2        1       0
3    6          0      0    2    0        1           3        1       1
4    2          1      2    0    0        2           1        1       0
5    0          1      2    0    0        0           1        1       0
6    0          1      2    1    0        3           1        1       0
7    1          1      2    1    1        2           3        1       1
8    2          1      2    1    1        1           1        2       0
9    3          1      2    0    0        1           1        2       1

  germination  ... externaldecay mycelium intdiscolor sclerotia fruitpods  \
0           2  ...             1        0           0         0         0
1           0  ...             1        0           0         0         0
2           0  ...             0        0           2         1         0
3           0  ...             0        0           2         1         0
4           2  ...             1        1           0         0         3
5           1  ...             1        0           0         0         3
6           2  ...             0        0           0         0         3
7           1  ...             1        0           0         0         3
8           2  ...             1        0           0         0         3
9           0  ...             0        0           0         0         3

  fruitspots roots Distrubution Predicted Class Prediction Correct?
0          4     0            1             1.0                 Yes
1          4     0            1             1.0                 Yes
2          4     0            2             2.0                 Yes
3          4     0            2             2.0                 Yes
4          4     0            3             3.0                 Yes
5          4     1            3             1.0                  No
6          4     1            4             4.0                 Yes
7          4     1            4             1.0                  No
8          4     1            4             4.0                 Yes
9          4     1            4             4.0                 Yes

[10 rows x 29 columns]

Learned Model (Likelihood Table):
                 0
plantstand01  1.00
plantstand11  0.00
plantstand02  1.00
plantstand12  0.00
plantstand03  0.25
...            ...
roots12       0.00
roots03       1.00
roots13       0.00
roots04       0.00
roots14       1.00

[224 rows x 1 columns]

Number of Test Instances:
10


Running Experiment 2 ...

Accuracy:
90.0%

Classifications:
  date plantstand precip temp hail crophist areadamaged severity seedtmt  \
0    3          0      2    1    0        1           0        2       1
1    6          0      2    1    0        1           0        1       0
2    5          0      0    2    1        2           2        1       0
3    3          0      0    2    1        0           2        1       0
4    2          1      2    0    0        3           1        2       0
5    4          0      2    0    1        0           1        2       0
6    3          1      1    0    0        2           1        2       1
7    0          1      1    1    1        2           1        2       1
8    2          1      1    0    0        3           1        2       0
9    0          1      2    1    1        1           1        1       0

  germination  ... externaldecay mycelium intdiscolor sclerotia fruitpods  \
0           2  ...             1        0           0         0         0
1           2  ...             1        0           0         0         0
2           2  ...             0        0           2         1         0
3           1  ...             0        0           2         1         0
4           1  ...             1        0           0         0         3
5           2  ...             1        1           0         0         3
6           2  ...             0        0           0         0         3
7           0  ...             1        0           0         0         3
8           2  ...             0        0           0         0         3
9           0  ...             1        0           0         0         3

  fruitspots roots Distrubution Predicted Class Prediction Correct?
0          4     0            1             1.0                 Yes
1          4     0            1             1.0                 Yes
2          4     0            2             2.0                 Yes
3          4     0            2             2.0                 Yes
4          4     0            3             3.0                 Yes
5          4     0            3             1.0                  No
6          4     1            4             4.0                 Yes
7          4     1            4             4.0                 Yes
8          4     1            4             4.0                 Yes
9          4     1            4             4.0                 Yes

[10 rows x 29 columns]

Learned Model (Likelihood Table):
                  0
plantstand01  1.000
plantstand11  0.000
plantstand02  1.000
plantstand12  0.000
plantstand03  0.125
...             ...
roots12       0.000
roots03       0.875
roots13       0.125
roots04       0.000
roots14       1.000

[224 rows x 1 columns]

Number of Test Instances:
10


Running Experiment 3 ...

Accuracy:
100.0%

Classifications:
  date plantstand precip temp hail crophist areadamaged severity seedtmt  \
0    3          0      2    1    0        2           1        1       0
1    3          0      2    1    0        2           0        2       1
2    4          0      0    1    1        1           3        1       1
3    5          0      0    2    1        3           3        1       1
4    2          1      2    0    0        3           1        2       0
5    3          0      2    0    1        3           1        2       0
6    1          1      2    0    0        0           1        2       1
7    0          1      2    1    0        3           1        1       0
8    0          1      1    1    0        1           1        1       0

  germination  ... externaldecay mycelium intdiscolor sclerotia fruitpods  \
0           1  ...             1        0           0         0         0
1           1  ...             1        0           0         0         0
2           1  ...             0        0           2         1         0
3           2  ...             0        0           2         1         0
4           2  ...             1        1           0         0         3
5           1  ...             1        1           0         0         3
6           0  ...             0        0           0         0         3
7           0  ...             0        0           0         0         3
8           0  ...             0        0           0         0         3

  fruitspots roots Distrubution Predicted Class Prediction Correct?
0          4     0            1             1.0                 Yes
1          4     0            1             1.0                 Yes
2          4     0            2             2.0                 Yes
3          4     0            2             2.0                 Yes
4          4     0            3             3.0                 Yes
5          4     0            3             3.0                 Yes
6          4     1            4             4.0                 Yes
7          4     1            4             4.0                 Yes
8          4     1            4             4.0                 Yes

[9 rows x 29 columns]

Learned Model (Likelihood Table):
                  0
plantstand01  1.000
plantstand11  0.000
plantstand02  1.000
plantstand12  0.000
plantstand03  0.125
...             ...
roots12       0.000
roots03       0.875
roots13       0.125
roots04       0.000
roots14       1.000

[224 rows x 1 columns]

Number of Test Instances:
9


Running Experiment 4 ...

Accuracy:
100.0%

Classifications:
  date plantstand precip temp hail crophist areadamaged severity seedtmt  \
0    5          0      2    1    0        2           0        1       1
1    5          0      2    1    0        3           1        1       1
2    6          0      0    1    1        3           3        1       1
3    5          0      0    2    0        3           2        1       0
4    0          1      2    0    0        2           1        1       1
5    0          1      2    0    0        1           1        2       1
6    1          1      2    1    1        3           1        2       0
7    1          1      2    1    0        0           1        2       1
8    2          1      2    0    0        1           1        2       0

  germination  ... externaldecay mycelium intdiscolor sclerotia fruitpods  \
0           0  ...             1        0           0         0         0
1           2  ...             1        0           0         0         0
2           0  ...             0        0           2         1         0
3           2  ...             0        0           2         1         0
4           1  ...             1        0           0         0         3
5           2  ...             1        0           0         0         3
6           1  ...             1        0           0         0         3
7           1  ...             0        0           0         0         3
8           0  ...             0        0           0         0         3

  fruitspots roots Distrubution Predicted Class Prediction Correct?
0          4     0            1             1.0                 Yes
1          4     0            1             1.0                 Yes
2          4     0            2             2.0                 Yes
3          4     0            2             2.0                 Yes
4          4     0            3             3.0                 Yes
5          4     0            3             3.0                 Yes
6          4     1            4             4.0                 Yes
7          4     1            4             4.0                 Yes
8          4     1            4             4.0                 Yes

[9 rows x 29 columns]

Learned Model (Likelihood Table):
                  0
plantstand01  1.000
plantstand11  0.000
plantstand02  1.000
plantstand12  0.000
plantstand03  0.250
...             ...
roots12       0.000
roots03       0.875
roots13       0.125
roots04       0.000
roots14       1.000

[224 rows x 1 columns]

Number of Test Instances:
9


Running Experiment 5 ...

Accuracy:
100.0%

Classifications:
  date plantstand precip temp hail crophist areadamaged severity seedtmt  \
0    6          0      2    1    0        3           0        1       1
1    3          0      0    1    0        1           2        1       0
2    4          0      0    1    0        2           3        1       1
3    0          1      2    0    0        0           1        1       1
4    0          1      2    0    0        1           1        1       1
5    1          1      2    0    0        3           1        1       1
6    3          1      2    0    0        2           1        2       1
7    2          1      2    1    1        3           1        2       1

  germination  ... externaldecay mycelium intdiscolor sclerotia fruitpods  \
0           1  ...             1        0           0         0         0
1           0  ...             0        0           2         1         0
2           1  ...             0        0           2         1         0
3           2  ...             1        0           0         0         3
4           1  ...             1        1           0         0         3
5           2  ...             0        0           0         0         3
6           1  ...             0        0           0         0         3
7           2  ...             1        0           0         0         3

  fruitspots roots Distrubution Predicted Class Prediction Correct?
0          4     0            1             1.0                 Yes
1          4     0            2             2.0                 Yes
2          4     0            2             2.0                 Yes
3          4     0            3             3.0                 Yes
4          4     0            3             3.0                 Yes
5          4     1            4             4.0                 Yes
6          4     1            4             4.0                 Yes
7          4     1            4             4.0                 Yes

[8 rows x 29 columns]

Learned Model (Likelihood Table):
                  0
plantstand01  1.000
plantstand11  0.000
plantstand02  1.000
plantstand12  0.000
plantstand03  0.250
...             ...
roots12       0.000
roots03       0.875
roots13       0.125
roots04       0.000
roots14       1.000

[224 rows x 1 columns]

Number of Test Instances:
8

Experiments Completed.


----------------------------------------------------------
Naive Bayes Summary Statistics
----------------------------------------------------------
Data Set : SoyBean.txt


Accuracy Statistics for All 5 Experiments:
[0.8 0.9 1.  1.  1. ]


Classification Accuracy : 94.0%

#### Vote

In [40]:
Data = Vote
DataPath = "Vote.txt"
TraceRunFile = "Bayes/Vote/TraceFile.txt"
StatsFile = "Bayes/Vote/TestStats.txt"
BayesMain.BayesMain(Data, DataPath, TraceRunFile, StatsFile)

Naive Bayes Program!


Running Experiment 1 ...

Accuracy:
85.1063829787234%

Classifications:
   Class Handicap Water Adoption Physician SalvadorAid ReligionInSchool  \
0      1        0     0        0         1           1                1
1      1        0     1        0         1           1                1
2      1        0     1        0         1           1                1
3      0        1     1        0         0           1                1
4      1        0     0        0         1           1                1
5      0        0     1        1         1           1                1
6      1        0     0        0         1           1                1
7      1        0     0        0         1           1                1
8      1        0     1        0         1           1                1
9      1        0     0        0         1           1                1
10     0        1     1        1         0           0                0
11     0        0     0        1         0           1                1
12     0        1     1        1         0           1                1
13     0        1     1        1         0           0                0
14     0        0     1        1         0           1                1
15     0        0     0        1         0           0                0
16     0        1     0        0         0           0                0
17     0        1     0        0         0           1                1
18     0        0     1        1         0           0                0
19     0        0     1        1         0           0                1
20     0        1     0        1         0           0                0
21     0        1     0        1         0           0                1
22     0        1     0        1         0           0                1
23     0        0     0        1         0           0                0
24     1        1     0        1         1           1                0
25     1        0     0        1         1           1                1
26     1        1     0        0         1           1                0
27     1        0     0        0         1           1                1
28     0        1     1        1         0           0                0
29     0        1     0        1         0           0                0
30     0        0     0        1         0           0                1
31     1        1     1        0         1           1                1
32     1        0     1        0         1           1                1
33     0        0     1        1         0           1                1
34     1        0     1        0         1           1                1
35     0        1     1        1         0           0                1
36     0        1     0        1         0           0                1
37     0        1     1        1         0           0                1
38     1        0     1        0         1           1                1
39     0        1     1        1         0           0                0
40     0        1     1        1         0           0                0
41     0        0     0        1         0           0                1
42     0        1     0        1         0           0                0
43     1        0     1        0         1           1                1
44     1        0     0        0         1           1                1
45     0        0     1        1         0           0                1
46     0        1     1        1         0           0                0

   SatelitteTestBan NicaraguanAid Missile Immigration CorpCutBack Education  \
0                 0             0       0           0           0         1
1                 0             0       0           1           1         1
2                 0             0       0           0           0         1
3                 0             0       0           0           1         1
4                 0             0       0           1           0         1
5                 0             0       0           1           1         0
6                 0             0       0           1           0         1
7                 0             0       0           1           0         1
8                 0             0       0           1           0         1
9                 0             0       0           1           0         1
10                1             1       1           0           0         0
11                0             0       0           1           1         1
12                0             1       0           0           1         0
13                1             1       1           0           1         0
14                0             1       0           0           0         0
15                1             1       1           0           0         0
16                1             1       1           1           0         0
17                1             0       0           1           1         0
18                1             1       1           1           1         0
19                1             1       1           1           0         0
20                1             1       1           0           0         0
21                1             1       0           1           1         0
22                1             1       1           1           1         0
23                1             1       1           0           0         0
24                1             0       1           1           0         0
25                0             0       0           1           0         1
26                1             0       0           1           0         0
27                1             1       0           1           0         1
28                1             1       1           0           0         0
29                1             1       1           1           0         0
30                1             1       1           1           1         0
31                0             0       0           0           0         0
32                0             0       0           0           0         1
33                1             0       1           1           1         0
34                1             0       0           0           0         1
35                1             1       1           0           0         0
36                1             1       0           0           0         1
37                1             1       1           1           1         0
38                0             0       0           1           0         1
39                1             1       0           1           0         0
40                0             1       1           0           1         0
41                1             1       1           0           1         0
42                1             1       1           1           0         0
43                0             0       0           1           0         1
44                1             1       1           1           0         1
45                1             1       0           1           0         0
46                1             1       1           1           1         0

   Sue Crime DutyFreeExport ExportAdmin  Predicted Class Prediction Correct?
0    1     1              0           0              0.0                 Yes
1    1     1              0           0              0.0                 Yes
2    1     1              0           0              0.0                 Yes
3    1     1              1           0              0.0                 Yes
4    1     1              0           0              0.0                 Yes
5    1     1              0           0              1.0                  No
6    1     1              0           0              0.0                 Yes
7    1     1              0           0              0.0                 Yes
8    1     1              0           0              0.0                 Yes
9    1     1              0           1              0.0                  No
10   0     0              0           1              1.0                 Yes
11   1     1              0           1              1.0                 Yes
12   1     0              1           1              1.0                 Yes
13   0     0              1           1              1.0                 Yes
14   0     0              0           1              1.0                 Yes
15   0     0              1           1              1.0                 Yes
16   0     0              1           1              1.0                 Yes
17   0     1              0           1              1.0                 Yes
18   0     0              1           1              1.0                 Yes
19   1     1              1           1              1.0                 Yes
20   0     0              0           1              1.0                 Yes
21   1     1              1           1              1.0                 Yes
22   0     1              1           1              1.0                 Yes
23   0     1              1           1              1.0                 Yes
24   1     1              0           1              1.0                 Yes
25   1     1              1           1              1.0                 Yes
26   0     1              1           1              1.0                 Yes
27   1     1              0           1              1.0                 Yes
28   0     0              1           1              1.0                 Yes
29   0     0              1           1              1.0                 Yes
30   1     1              0           1              1.0                 Yes
31   1     1              0           1              0.0                  No
32   1     1              0           1              0.0                  No
33   1     1              0           1              1.0                 Yes
34   1     1              0           1              0.0                  No
35   0     0              1           1              1.0                 Yes
36   1     0              0           1              1.0                 Yes
37   1     1              1           1              1.0                 Yes
38   1     1              0           1              0.0                  No
39   0     0              0           1              1.0                 Yes
40   0     0              1           1              1.0                 Yes
41   0     1              1           1              1.0                 Yes
42   0     0              1           1              1.0                 Yes
43   1     1              0           1              0.0                  No
44   1     1              0           1              1.0                 Yes
45   0     0              1           1              1.0                 Yes
46   0     0              0           1              1.0                 Yes

Learned Model (Likelihood Table):
                           0
Handicap10          0.176471
Handicap00          0.823529
Handicap11          0.456954
Handicap01          0.543046
Water10             0.500000
Water00             0.500000
Water11             0.437086
Water01             0.562914
Adoption00          1.000000
Adoption10          0.000000
Adoption01          0.370861
Adoption11          0.629139
Physician10         0.911765
Physician00         0.088235
Physician11         0.417219
Physician01         0.582781
SalvadorAid10       0.941176
SalvadorAid00       0.058824
SalvadorAid11       0.470199
SalvadorAid01       0.529801
ReligionInSchool10  0.911765
ReligionInSchool00  0.088235
ReligionInSchool11  0.569536
ReligionInSchool01  0.430464
SatelitteTestBan00  0.970588
SatelitteTestBan10  0.029412
SatelitteTestBan01  0.370861
SatelitteTestBan11  0.629139
NicaraguanAid00     0.941176
NicaraguanAid10     0.058824
NicaraguanAid01     0.397351
NicaraguanAid11     0.602649
Missile00           0.941176
Missile10           0.058824
Missile01           0.403974
Missile11           0.596026
Immigration10       0.382353
Immigration00       0.617647
Immigration11       0.569536
Immigration01       0.430464
CorpCutBack00       0.735294
CorpCutBack10       0.264706
CorpCutBack01       0.635762
CorpCutBack11       0.364238
Education10         0.911765
Education00         0.088235
Education11         0.390728
Education01         0.609272
Sue10               0.911765
Sue00               0.088235
Sue11               0.456954
Sue01               0.543046
Crime10             0.941176
Crime00             0.058824
Crime11             0.576159
Crime01             0.423841
DutyFreeExport00    0.882353
DutyFreeExport10    0.117647
DutyFreeExport01    0.589404
DutyFreeExport11    0.410596

Number of Test Instances:
47


Running Experiment 2 ...

Accuracy:
72.3404255319149%

Classifications:
   Class Handicap Water Adoption Physician SalvadorAid ReligionInSchool  \
0      1        1     1        0         1           1                1
1      1        0     1        0         1           1                1
2      1        1     1        0         1           1                1
3      1        0     1        0         1           1                1
4      1        0     0        0         1           1                0
5      1        0     1        0         1           1                1
6      1        0     0        0         1           1                1
7      1        0     0        0         1           1                0
8      1        0     1        0         1           1                1
9      1        0     0        0         1           1                1
10     1        0     0        0         1           1                1
11     0        1     0        1         0           1                1
12     1        1     1        0         1           1                1
13     0        1     0        1         0           0                0
14     0        1     1        1         0           0                0
15     0        1     1        1         0           0                0
16     0        1     0        1         0           0                0
17     0        1     0        1         0           0                0
18     0        0     1        1         0           0                0
19     1        0     0        0         1           1                1
20     0        1     0        1         0           0                0
21     1        0     1        0         1           1                1
22     0        0     0        1         0           0                0
23     0        1     0        1         0           1                1
24     1        0     1        0         1           1                1
25     1        0     0        0         1           1                0
26     1        0     0        0         1           1                1
27     1        1     1        0         1           1                1
28     1        1     1        0         1           1                1
29     1        0     1        1         1           1                1
30     1        0     0        0         1           1                0
31     0        1     0        1         0           0                0
32     1        0     0        0         1           1                1
33     0        1     0        1         0           0                0
34     0        1     1        1         0           0                0
35     1        0     0        1         1           1                1
36     0        1     0        1         0           0                1
37     0        0     1        1         0           1                1
38     0        0     1        1         0           0                1
39     1        1     0        0         1           1                0
40     1        0     1        0         1           1                1
41     0        1     1        1         0           0                0
42     1        0     0        1         1           1                1
43     1        1     0        0         0           0                0
44     1        1     1        0         1           1                1
45     1        1     0        1         1           1                1
46     0        0     0        1         0           0                0

   SatelitteTestBan NicaraguanAid Missile Immigration CorpCutBack Education  \
0                 0             0       0           1           0         1
1                 0             0       0           0           0         1
2                 0             0       0           1           1         0
3                 0             0       0           0           1         1
4                 0             0       0           1           0         1
5                 0             0       0           1           0         1
6                 0             0       0           1           0         1
7                 0             0       0           0           0         1
8                 0             0       0           0           0         1
9                 0             0       0           0           0         1
10                0             0       0           1           0         1
11                0             0       0           0           0         0
12                0             0       0           1           0         0
13                1             1       1           0           1         0
14                1             1       1           0           0         0
15                1             1       1           1           0         0
16                1             1       1           1           0         0
17                1             1       1           1           0         0
18                0             1       1           1           1         0
19                1             0       0           1           0         0
20                1             1       1           0           0         0
21                0             0       0           1           1         1
22                1             1       1           1           0         0
23                1             0       0           0           1         0
24                0             0       0           1           1         1
25                1             1       1           1           0         1
26                0             0       0           0           0         1
27                0             0       0           0           1         1
28                0             0       0           1           0         1
29                1             0       1           1           0         1
30                1             0       1           1           0         0
31                1             1       1           1           0         0
32                0             0       0           1           1         1
33                1             1       1           0           0         0
34                1             1       1           0           0         0
35                0             0       1           1           0         1
36                1             1       1           1           0         0
37                0             0       0           0           0         0
38                0             1       1           1           0         0
39                1             1       1           0           0         1
40                0             0       0           0           0         1
41                1             1       1           0           1         0
42                1             0       0           0           0         1
43                1             1       1           1           0         0
44                0             0       0           0           1         0
45                1             1       0           1           0         1
46                1             1       1           0           1         0

   Sue Crime DutyFreeExport ExportAdmin  Predicted Class Prediction Correct?
0    1     1              0           0              0.0                 Yes
1    1     1              0           0              0.0                 Yes
2    1     0              0           0              1.0                  No
3    1     1              0           0              0.0                 Yes
4    1     1              0           0              0.0                 Yes
5    1     1              0           0              0.0                 Yes
6    1     1              0           0              0.0                 Yes
7    0     1              0           0              0.0                 Yes
8    1     1              0           0              0.0                 Yes
9    1     1              0           1              0.0                  No
10   0     1              0           1              0.0                  No
11   0     0              0           1              1.0                 Yes
12   1     1              0           1              0.0                  No
13   0     0              1           1              1.0                 Yes
14   0     0              1           1              1.0                 Yes
15   0     0              1           1              1.0                 Yes
16   0     0              1           1              1.0                 Yes
17   0     0              0           1              1.0                 Yes
18   0     0              1           1              1.0                 Yes
19   0     1              1           1              1.0                 Yes
20   0     0              1           1              1.0                 Yes
21   1     1              0           1              0.0                  No
22   0     0              0           1              1.0                 Yes
23   0     1              0           1              1.0                 Yes
24   1     1              0           1              0.0                  No
25   1     1              0           1              1.0                 Yes
26   1     1              0           1              0.0                  No
27   1     1              0           1              0.0                  No
28   1     1              0           1              0.0                  No
29   1     1              0           1              1.0                 Yes
30   0     1              0           1              1.0                 Yes
31   0     0              0           1              1.0                 Yes
32   0     1              0           1              0.0                  No
33   0     0              0           1              1.0                 Yes
34   0     0              1           1              1.0                 Yes
35   1     1              0           1              0.0                  No
36   1     0              0           1              1.0                 Yes
37   1     1              1           1              1.0                 Yes
38   1     1              0           1              1.0                 Yes
39   1     1              0           1              1.0                 Yes
40   1     1              0           1              0.0                  No
41   0     0              1           1              1.0                 Yes
42   1     1              0           1              1.0                 Yes
43   0     1              0           1              1.0                 Yes
44   1     1              0           1              0.0                  No
45   0     1              1           1              1.0                 Yes
46   0     0              1           1              1.0                 Yes

Learned Model (Likelihood Table):
                           0
Handicap00          0.852941
Handicap10          0.147059
Handicap01          0.543046
Handicap11          0.456954
Water00             0.529412
Water10             0.470588
Water01             0.536424
Water11             0.463576
Adoption00          0.970588
Adoption10          0.029412
Adoption01          0.337748
Adoption11          0.662252
Physician10         0.882353
Physician00         0.117647
Physician11         0.364238
Physician01         0.635762
SalvadorAid10       0.941176
SalvadorAid00       0.058824
SalvadorAid11       0.430464
SalvadorAid01       0.569536
ReligionInSchool10  0.970588
ReligionInSchool00  0.029412
ReligionInSchool11  0.582781
ReligionInSchool01  0.417219
SatelitteTestBan00  0.970588
SatelitteTestBan10  0.029412
SatelitteTestBan01  0.331126
SatelitteTestBan11  0.668874
NicaraguanAid00     0.941176
NicaraguanAid10     0.058824
NicaraguanAid01     0.350993
NicaraguanAid11     0.649007
Missile00           0.941176
Missile10           0.058824
Missile01           0.403974
Missile11           0.596026
Immigration00       0.588235
Immigration10       0.411765
Immigration01       0.417219
Immigration11       0.582781
CorpCutBack00       0.705882
CorpCutBack10       0.294118
CorpCutBack01       0.615894
CorpCutBack11       0.384106
Education10         0.911765
Education00         0.088235
Education11         0.357616
Education01         0.642384
Sue10               0.941176
Sue00               0.058824
Sue11               0.463576
Sue01               0.536424
Crime10             0.970588
Crime00             0.029412
Crime11             0.562914
Crime01             0.437086
DutyFreeExport00    0.852941
DutyFreeExport10    0.147059
DutyFreeExport01    0.543046
DutyFreeExport11    0.456954

Number of Test Instances:
47


Running Experiment 3 ...

Accuracy:
70.2127659574468%

Classifications:
   Class Handicap Water Adoption Physician SalvadorAid ReligionInSchool  \
0      1        0     1        0         1           1                1
1      1        1     0        0         1           1                1
2      1        0     0        0         1           1                1
3      0        0     0        0         0           0                1
4      1        0     0        0         1           1                1
5      1        0     0        0         1           1                1
6      1        0     0        0         1           1                1
7      1        0     1        0         1           1                1
8      1        0     0        0         1           1                1
9      0        1     1        1         0           0                1
10     0        0     0        1         0           0                0
11     0        1     1        1         0           0                0
12     1        0     1        0         1           1                1
13     0        1     0        1         0           0                0
14     1        1     1        0         1           1                1
15     1        0     1        0         1           1                1
16     0        0     1        1         0           0                1
17     1        0     0        1         1           1                1
18     1        0     0        1         1           1                1
19     0        0     0        1         0           0                0
20     1        0     0        1         1           1                1
21     1        0     1        0         1           1                1
22     1        0     1        1         1           1                1
23     0        0     1        1         0           0                0
24     1        0     0        0         1           1                1
25     0        0     0        1         0           0                0
26     0        1     1        1         1           1                1
27     0        1     1        0         1           0                0
28     0        1     1        1         0           0                0
29     1        1     1        0         1           1                1
30     0        1     0        1         0           0                0
31     0        0     1        1         0           1                1
32     0        0     0        1         0           0                1
33     1        0     1        0         1           1                1
34     1        0     0        0         1           1                1
35     0        0     0        1         0           0                0
36     0        0     0        1         0           0                1
37     0        0     0        1         0           0                1
38     0        0     0        1         0           0                0
39     0        1     0        1         0           0                0
40     0        1     0        1         0           0                0
41     1        0     0        0         1           1                0
42     1        0     1        0         1           1                1
43     0        1     1        1         0           0                1
44     1        0     0        0         1           1                1
45     1        0     1        0         1           1                1
46     0        1     0        1         0           0                0

   SatelitteTestBan NicaraguanAid Missile Immigration CorpCutBack Education  \
0                 0             0       0           1           0         1
1                 0             0       0           0           1         1
2                 0             0       0           0           0         1
3                 0             1       1           0           1         1
4                 0             0       0           0           0         1
5                 0             0       0           0           0         1
6                 0             0       0           0           0         1
7                 0             0       0           0           0         1
8                 0             0       0           0           0         1
9                 1             1       1           1           0         0
10                1             1       1           1           1         0
11                1             1       1           0           0         0
12                0             0       0           0           0         1
13                1             1       1           0           0         0
14                1             0       0           0           0         1
15                0             0       0           1           0         1
16                0             1       1           1           1         0
17                1             1       1           1           0         1
18                1             0       0           1           1         1
19                1             1       1           1           1         0
20                1             1       0           1           0         0
21                0             0       1           1           0         1
22                0             0       0           1           0         1
23                0             1       1           0           1         0
24                0             0       0           1           0         1
25                1             1       1           1           0         0
26                0             0       0           0           1         1
27                1             1       1           0           1         0
28                1             1       1           0           0         0
29                0             0       0           1           0         1
30                1             1       1           1           0         0
31                1             1       0           0           1         0
32                1             1       1           0           1         0
33                0             0       0           0           0         1
34                1             0       0           1           0         1
35                1             1       1           0           1         0
36                1             1       1           1           0         0
37                1             1       1           1           0         1
38                1             1       1           0           0         0
39                1             0       1           1           1         0
40                1             1       1           1           1         0
41                0             0       0           0           0         1
42                0             0       0           0           0         1
43                1             1       1           1           1         1
44                0             0       0           1           0         1
45                1             1       0           0           1         1
46                1             1       1           0           0         0

   Sue Crime DutyFreeExport ExportAdmin  Predicted Class Prediction Correct?
0    1     1              0           0              0.0                 Yes
1    1     1              0           0              0.0                 Yes
2    1     1              0           0              0.0                 Yes
3    1     1              1           0              1.0                  No
4    1     1              0           0              0.0                 Yes
5    1     1              0           0              0.0                 Yes
6    1     1              0           0              0.0                 Yes
7    1     1              0           0              0.0                 Yes
8    1     1              1           0              0.0                 Yes
9    0     0              0           1              1.0                 Yes
10   0     0              1           1              1.0                 Yes
11   0     0              0           1              1.0                 Yes
12   1     1              0           1              0.0                  No
13   0     0              1           1              1.0                 Yes
14   1     1              0           1              0.0                  No
15   1     1              0           1              0.0                  No
16   1     0              1           1              1.0                 Yes
17   1     1              1           1              1.0                 Yes
18   1     1              0           1              1.0                 Yes
19   0     0              1           1              1.0                 Yes
20   0     1              0           1              1.0                 Yes
21   1     1              0           1              0.0                  No
22   1     1              0           1              0.0                  No
23   0     1              1           1              1.0                 Yes
24   1     1              0           1              0.0                  No
25   0     0              1           1              1.0                 Yes
26   1     1              0           1              0.0                  No
27   0     1              0           1              1.0                 Yes
28   0     0              1           1              1.0                 Yes
29   1     1              0           1              0.0                  No
30   0     0              0           1              1.0                 Yes
31   1     0              1           1              1.0                 Yes
32   0     0              1           1              1.0                 Yes
33   1     1              0           1              0.0                  No
34   1     1              0           1              0.0                  No
35   0     0              1           1              1.0                 Yes
36   0     1              0           1              1.0                 Yes
37   0     0              0           1              1.0                 Yes
38   0     0              1           1              1.0                 Yes
39   0     0              1           1              1.0                 Yes
40   0     0              1           1              1.0                 Yes
41   1     1              0           1              0.0                  No
42   1     1              0           1              0.0                  No
43   1     0              0           1              1.0                 Yes
44   0     1              0           1              0.0                  No
45   1     1              1           1              1.0                 Yes
46   0     0              1           1              1.0                 Yes

Learned Model (Likelihood Table):
                           0
Handicap00          0.823529
Handicap10          0.176471
Handicap01          0.496689
Handicap11          0.503311
Water00             0.411765
Water10             0.588235
Water01             0.556291
Water11             0.443709
Adoption00          0.970588
Adoption10          0.029412
Adoption01          0.357616
Adoption11          0.642384
Physician10         0.911765
Physician00         0.088235
Physician11         0.370861
Physician01         0.629139
SalvadorAid10       0.970588
SalvadorAid00       0.029412
SalvadorAid11       0.456954
SalvadorAid01       0.543046
ReligionInSchool10  0.911765
ReligionInSchool00  0.088235
ReligionInSchool11  0.569536
ReligionInSchool01  0.430464
SatelitteTestBan00  0.970588
SatelitteTestBan10  0.029412
SatelitteTestBan01  0.350993
SatelitteTestBan11  0.649007
NicaraguanAid00     0.970588
NicaraguanAid10     0.029412
NicaraguanAid01     0.377483
NicaraguanAid11     0.622517
Missile00           0.970588
Missile10           0.029412
Missile01           0.410596
Missile11           0.589404
Immigration00       0.470588
Immigration10       0.529412
Immigration01       0.417219
Immigration11       0.582781
CorpCutBack00       0.705882
CorpCutBack10       0.294118
CorpCutBack01       0.642384
CorpCutBack11       0.357616
Education10         0.882353
Education00         0.117647
Education11         0.337748
Education01         0.662252
Sue10               0.911765
Sue00               0.088235
Sue11               0.456954
Sue01               0.543046
Crime10             0.941176
Crime00             0.058824
Crime11             0.582781
Crime01             0.417219
DutyFreeExport00    0.911765
DutyFreeExport10    0.088235
DutyFreeExport01    0.569536
DutyFreeExport11    0.430464

Number of Test Instances:
47


Running Experiment 4 ...

Accuracy:
76.08695652173914%

Classifications:
   Class Handicap Water Adoption Physician SalvadorAid ReligionInSchool  \
0      1        0     1        0         1           1                1
1      1        1     1        0         1           1                1
2      1        0     0        0         1           1                1
3      0        0     1        0         1           1                1
4      0        0     0        0         1           1                1
5      1        0     0        0         1           1                1
6      1        0     0        0         1           1                1
7      1        0     1        0         1           1                1
8      0        0     0        1         0           0                0
9      1        0     1        0         1           1                1
10     0        1     0        0         0           0                1
11     1        0     1        0         1           1                1
12     0        0     0        0         0           1                1
13     1        0     0        0         1           1                1
14     1        0     1        0         1           1                1
15     1        0     0        0         1           1                1
16     1        1     1        1         1           1                1
17     0        1     0        1         0           0                1
18     0        0     1        1         0           0                1
19     0        1     0        1         0           0                0
20     1        0     0        0         1           1                1
21     1        0     0        0         1           1                1
22     0        0     0        0         0           0                0
23     1        1     1        0         1           1                1
24     0        1     0        1         0           0                0
25     1        1     0        1         1           0                0
26     0        1     0        1         0           0                0
27     0        1     0        1         0           0                0
28     0        0     0        1         0           0                0
29     0        1     0        1         0           0                0
30     0        0     0        1         0           0                1
31     0        1     1        1         0           1                1
32     0        1     1        1         0           0                0
33     1        0     1        1         1           1                1
34     1        0     0        0         1           1                1
35     0        1     0        1         0           0                0
36     0        0     0        1         0           0                1
37     0        1     1        1         0           0                0
38     0        0     0        1         0           0                1
39     0        1     0        1         0           0                0
40     0        1     0        1         0           0                1
41     0        1     1        1         0           1                1
42     1        0     0        0         1           1                1
43     0        1     1        1         0           0                0
44     1        0     0        0         1           1                1
45     1        0     0        0         1           0                0

   SatelitteTestBan NicaraguanAid Missile Immigration CorpCutBack Education  \
0                 0             0       0           0           0         1
1                 1             0       0           0           0         1
2                 0             0       0           0           0         1
3                 0             0       0           0           1         1
4                 0             0       0           0           1         1
5                 0             0       0           1           0         1
6                 0             0       0           1           0         1
7                 0             0       0           0           0         1
8                 1             1       1           1           0         0
9                 0             0       0           1           0         1
10                1             1       1           1           0         0
11                0             0       0           0           0         1
12                1             0       0           0           0         1
13                0             0       0           0           0         1
14                0             0       0           1           1         1
15                0             0       0           1           0         1
16                1             1       0           1           0         0
17                1             1       1           1           1         0
18                1             1       1           0           1         0
19                1             1       1           0           1         0
20                0             0       0           0           0         1
21                0             0       0           1           0         1
22                1             1       1           1           0         1
23                0             0       0           1           0         1
24                1             1       1           1           0         0
25                0             1       1           1           0         0
26                1             1       1           1           0         0
27                1             1       1           1           1         0
28                1             1       1           0           0         0
29                1             1       1           1           1         0
30                0             1       1           1           0         0
31                0             1       1           1           1         0
32                1             1       1           1           0         0
33                1             1       1           0           0         1
34                0             0       0           0           1         1
35                1             1       1           1           1         0
36                1             1       1           0           0         0
37                1             1       0           0           0         0
38                1             1       1           1           0         0
39                1             1       1           1           1         0
40                1             1       1           1           1         0
41                0             0       0           1           1         0
42                0             0       0           1           0         1
43                1             1       1           0           1         0
44                1             0       0           1           0         1
45                1             1       1           1           0         0

   Sue Crime DutyFreeExport ExportAdmin  Predicted Class Prediction Correct?
0    1     1              0           0              0.0                 Yes
1    1     1              0           0              1.0                  No
2    1     1              0           0              0.0                 Yes
3    0     1              0           0              0.0                 Yes
4    1     1              0           0              0.0                 Yes
5    1     1              1           0              0.0                 Yes
6    1     1              0           0              0.0                 Yes
7    1     1              0           0              0.0                 Yes
8    0     1              0           1              1.0                 Yes
9    1     1              0           1              0.0                  No
10   0     1              1           1              1.0                 Yes
11   1     1              0           1              0.0                  No
12   1     1              0           1              1.0                 Yes
13   1     1              0           1              0.0                  No
14   1     0              0           1              0.0                  No
15   1     1              0           1              0.0                  No
16   1     1              0           1              1.0                 Yes
17   0     0              0           1              1.0                 Yes
18   0     1              1           1              1.0                 Yes
19   0     0              1           1              1.0                 Yes
20   1     1              0           1              0.0                  No
21   0     1              0           1              0.0                  No
22   1     1              1           1              1.0                 Yes
23   1     1              0           1              0.0                  No
24   0     0              1           1              1.0                 Yes
25   0     1              1           1              1.0                 Yes
26   0     1              1           1              1.0                 Yes
27   0     1              1           1              1.0                 Yes
28   0     0              1           1              1.0                 Yes
29   0     1              0           1              1.0                 Yes
30   0     1              0           1              1.0                 Yes
31   0     0              0           1              1.0                 Yes
32   1     0              1           1              1.0                 Yes
33   1     1              0           1              1.0                 Yes
34   1     1              0           1              0.0                  No
35   0     0              1           1              1.0                 Yes
36   0     0              1           1              1.0                 Yes
37   0     1              0           1              1.0                 Yes
38   1     0              0           1              1.0                 Yes
39   1     0              1           1              1.0                 Yes
40   0     0              1           1              1.0                 Yes
41   1     1              0           1              1.0                 Yes
42   1     1              0           1              0.0                  No
43   0     0              1           1              1.0                 Yes
44   0     1              1           1              1.0                 Yes
45   1     1              0           1              1.0                 Yes

Learned Model (Likelihood Table):
                           0
Handicap00          0.828571
Handicap10          0.171429
Handicap01          0.529801
Handicap11          0.470199
Water00             0.485714
Water10             0.514286
Water01             0.516556
Water11             0.483444
Adoption00          0.971429
Adoption10          0.028571
Adoption01          0.344371
Adoption11          0.655629
Physician10         0.885714
Physician00         0.114286
Physician11         0.390728
Physician01         0.609272
SalvadorAid10       0.942857
SalvadorAid00       0.057143
SalvadorAid11       0.470199
SalvadorAid01       0.529801
ReligionInSchool10  0.914286
ReligionInSchool00  0.085714
ReligionInSchool11  0.569536
ReligionInSchool01  0.430464
SatelitteTestBan00  1.000000
SatelitteTestBan10  0.000000
SatelitteTestBan01  0.344371
SatelitteTestBan11  0.655629
NicaraguanAid00     0.942857
NicaraguanAid10     0.057143
NicaraguanAid01     0.390728
NicaraguanAid11     0.609272
Missile00           0.942857
Missile10           0.057143
Missile01           0.417219
Missile11           0.582781
Immigration00       0.514286
Immigration10       0.485714
Immigration01       0.450331
Immigration11       0.549669
CorpCutBack00       0.714286
CorpCutBack10       0.285714
CorpCutBack01       0.635762
CorpCutBack11       0.364238
Education10         0.885714
Education00         0.114286
Education11         0.364238
Education01         0.635762
Sue10               0.942857
Sue00               0.057143
Sue11               0.456954
Sue01               0.543046
Crime10             0.942857
Crime00             0.057143
Crime11             0.549669
Crime01             0.450331
DutyFreeExport00    0.885714
DutyFreeExport10    0.114286
DutyFreeExport01    0.569536
DutyFreeExport11    0.430464

Number of Test Instances:
46


Running Experiment 5 ...

Accuracy:
80.0%

Classifications:
   Class Handicap Water Adoption Physician SalvadorAid ReligionInSchool  \
0      1        0     0        0         1           1                1
1      1        0     0        0         1           1                1
2      0        0     1        0         0           1                1
3      0        1     1        0         0           0                0
4      1        1     0        0         1           1                1
5      1        0     1        0         1           1                1
6      1        0     1        0         1           1                1
7      1        0     1        0         1           1                1
8      0        1     0        1         0           0                0
9      0        1     1        1         0           0                0
10     1        0     0        0         1           1                1
11     0        1     0        1         0           0                0
12     0        1     1        1         0           0                0
13     1        1     1        1         1           1                0
14     0        0     1        0         0           1                1
15     1        0     1        0         1           1                1
16     0        1     0        1         0           1                1
17     1        0     1        0         1           1                1
18     0        0     1        0         0           0                1
19     0        1     1        1         0           0                0
20     1        0     0        1         1           0                0
21     0        1     1        1         0           0                0
22     0        1     0        1         0           0                0
23     0        1     0        1         0           0                1
24     0        1     1        1         0           0                0
25     0        0     0        0         0           0                1
26     1        1     1        1         1           0                0
27     0        0     1        1         0           0                0
28     0        0     1        0         0           0                0
29     0        0     0        1         0           0                0
30     0        1     1        1         0           1                1
31     0        1     0        1         0           0                0
32     1        0     1        0         1           1                1
33     0        0     0        1         0           0                0
34     0        0     1        1         0           1                1
35     0        1     1        1         0           0                0
36     1        0     1        0         1           1                1
37     1        0     0        0         1           1                1
38     0        0     1        1         0           0                1
39     0        1     0        0         0           1                1
40     0        0     0        1         0           0                1
41     0        0     0        0         0           1                1
42     1        1     0        1         1           1                1
43     0        0     1        1         1           1                1
44     0        1     1        1         0           0                0

   SatelitteTestBan NicaraguanAid Missile Immigration CorpCutBack Education  \
0                 0             0       0           0           0         1
1                 0             0       0           0           0         1
2                 0             0       0           1           1         0
3                 0             1       1           0           1         0
4                 0             0       0           1           0         1
5                 0             0       0           1           0         1
6                 0             0       0           1           0         1
7                 0             0       0           1           1         1
8                 1             1       1           1           0         0
9                 1             1       1           0           1         0
10                0             0       0           0           0         1
11                1             1       1           1           0         0
12                1             1       1           1           1         0
13                1             0       0           0           0         1
14                0             0       0           0           0         1
15                0             0       0           0           0         1
16                0             0       1           1           0         0
17                0             0       0           0           0         1
18                1             0       1           0           1         0
19                1             1       1           0           0         0
20                1             1       1           1           0         0
21                1             1       1           0           1         0
22                1             1       1           0           0         0
23                1             1       1           0           0         0
24                1             1       1           0           1         0
25                1             1       1           0           1         0
26                1             1       1           1           1         0
27                1             1       1           1           0         0
28                1             1       1           1           1         0
29                1             1       1           1           1         0
30                0             1       0           1           1         0
31                0             1       1           1           0         0
32                0             0       0           0           0         0
33                1             1       1           1           0         0
34                1             0       0           0           1         1
35                1             1       1           1           0         0
36                1             0       0           0           1         1
37                0             0       0           1           0         1
38                0             1       1           0           1         0
39                0             0       0           0           1         1
40                1             1       1           1           1         0
41                0             0       0           1           1         1
42                1             1       0           1           1         1
43                0             1       1           1           1         1
44                1             1       1           0           0         0

   Sue Crime DutyFreeExport ExportAdmin  Predicted Class Prediction Correct?
0    1     1              0           0              0.0                 Yes
1    1     1              0           0              0.0                 Yes
2    1     1              0           0              0.0                 Yes
3    0     0              1           0              1.0                  No
4    1     1              0           0              0.0                 Yes
5    1     1              0           0              0.0                 Yes
6    1     1              0           0              0.0                 Yes
7    1     1              0           0              0.0                 Yes
8    0     0              1           1              1.0                 Yes
9    0     0              0           1              1.0                 Yes
10   1     1              0           1              0.0                  No
11   0     1              1           1              1.0                 Yes
12   1     0              0           1              1.0                 Yes
13   1     1              0           1              1.0                 Yes
14   1     1              1           1              0.0                  No
15   1     1              0           1              0.0                  No
16   1     1              0           1              1.0                 Yes
17   1     1              0           1              0.0                  No
18   0     0              1           1              1.0                 Yes
19   0     0              1           1              1.0                 Yes
20   0     1              1           1              1.0                 Yes
21   0     0              1           1              1.0                 Yes
22   0     0              0           1              1.0                 Yes
23   0     0              1           1              1.0                 Yes
24   0     0              0           1              1.0                 Yes
25   0     1              1           1              1.0                 Yes
26   0     1              0           1              1.0                 Yes
27   0     0              1           1              1.0                 Yes
28   0     0              1           1              1.0                 Yes
29   0     0              1           1              1.0                 Yes
30   1     1              1           1              1.0                 Yes
31   0     0              1           1              1.0                 Yes
32   1     1              0           1              0.0                  No
33   1     0              1           1              1.0                 Yes
34   1     1              0           1              1.0                 Yes
35   1     0              0           1              1.0                 Yes
36   1     1              0           1              0.0                  No
37   0     1              0           1              0.0                  No
38   1     0              1           1              1.0                 Yes
39   0     1              0           1              1.0                 Yes
40   0     0              1           1              1.0                 Yes
41   1     1              0           1              0.0                  No
42   0     1              1           1              1.0                 Yes
43   1     1              0           1              1.0                 Yes
44   0     0              0           1              1.0                 Yes

Learned Model (Likelihood Table):
                           0
Handicap00          0.857143
Handicap10          0.142857
Handicap01          0.532895
Handicap11          0.467105
Water00             0.514286
Water10             0.485714
Water01             0.578947
Water11             0.421053
Adoption00          0.971429
Adoption10          0.028571
Adoption01          0.361842
Adoption11          0.638158
Physician10         0.942857
Physician00         0.057143
Physician11         0.414474
Physician01         0.585526
SalvadorAid10       0.971429
SalvadorAid00       0.028571
SalvadorAid11       0.473684
SalvadorAid01       0.526316
ReligionInSchool10  0.942857
ReligionInSchool00  0.057143
ReligionInSchool11  0.592105
ReligionInSchool01  0.407895
SatelitteTestBan00  0.971429
SatelitteTestBan10  0.028571
SatelitteTestBan01  0.348684
SatelitteTestBan11  0.651316
NicaraguanAid00     0.971429
NicaraguanAid10     0.028571
NicaraguanAid01     0.388158
NicaraguanAid11     0.611842
Missile00           0.971429
Missile10           0.028571
Missile01           0.427632
Missile11           0.572368
Immigration00       0.600000
Immigration10       0.400000
Immigration01       0.401316
Immigration11       0.598684
CorpCutBack00       0.742857
CorpCutBack10       0.257143
CorpCutBack01       0.671053
CorpCutBack11       0.328947
Education10         0.942857
Education00         0.057143
Education11         0.375000
Education01         0.625000
Sue10               0.942857
Sue00               0.057143
Sue11               0.467105
Sue01               0.532895
Crime10             0.971429
Crime00             0.028571
Crime11             0.585526
Crime01             0.414474
DutyFreeExport00    0.885714
DutyFreeExport10    0.114286
DutyFreeExport01    0.585526
DutyFreeExport11    0.414474

Number of Test Instances:
45

Experiments Completed.


----------------------------------------------------------
Naive Bayes Summary Statistics
----------------------------------------------------------
Data Set : Vote.txt


Accuracy Statistics for All 5 Experiments:
[0.85106383 0.72340426 0.70212766 0.76086957 0.8       ]


Classification Accuracy : 76.74930619796484%